// Generated by npm run i18n:sync. Do not edit.
import locale0 from './locales/en.json';
import locale1 from './locales/de.json';

export const localeCatalogs = {
  'en': locale0,
  'de': locale1,
} as const;

export const LANGUAGE_OPTIONS = [
  { code: 'en', label: 'English' },
  { code: 'de', label: 'Deutsch' },
] as const;

export const SUPPORTED_LANGUAGES = [
  'en',
  'de',
] as const;
