import {
  // Finance & Banking
  IconCreditCard,
  IconBuildingBank,
  IconWallet,
  IconCoin,
  IconCash,
  IconPigMoney,
  IconReportMoney,
  IconReceipt,
  IconCurrencyDollar,
  IconCurrencyEuro,
  IconCurrencyPound,
  IconCurrencyYen,

  // Home & Property
  IconHome,
  IconBuildingSkyscraper,
  IconBuildingCottage,
  IconParking,
  IconPool,
  IconFence,
  IconLadder,

  // Utilities
  IconBulb,
  IconDroplet,
  IconFlame,
  IconWifi,
  IconDeviceTv,
  IconTrash,
  IconRecycle,
  IconPlug,
  IconBatteryCharging,
  IconSolarPanel,
  IconWind,

  // Vehicles
  IconCar,
  IconTruck,
  IconCaravan,
  IconMotorbike,
  IconScooter,
  IconBike,
  IconBus,
  IconPlane,
  IconHelicopter,
  IconSailboat,
  IconKayak,
  IconGasStation,
  IconCarCrash,
  IconWash,

  // Sports & Activities
  IconBallFootball,
  IconBallBaseball,
  IconBallBasketball,
  IconBallTennis,
  IconBallVolleyball,
  IconBallBowling,
  IconPlayFootball,
  IconGolf,
  IconSwimming,
  IconIceSkating,
  IconSkiJumping,
  IconGymnastics,
  IconRun,
  IconBarbell,
  IconTrophy,
  IconMedal,
  IconAward,

  // Healthcare & Medical
  IconHeartbeat,
  IconHeartRateMonitor,
  IconPill,
  IconVaccine,
  IconDental,
  IconStethoscope,
  IconAmbulance,
  IconFirstAidKit,
  IconBandage,
  IconThermometer,
  IconEye,
  IconEyeglass,
  IconDisabled,
  IconLeaf,

  // Shopping
  IconShoppingCart,

  // Entertainment
  IconMovie,
  IconMusic,
  IconDeviceGamepad2,
  IconBook,
  IconBackpack,
  IconNotebook,
  IconGift,

  // Technology
  IconPhone,
  IconDeviceMobile,
  IconDeviceLaptop,
  IconDeviceDesktop,
  IconDeviceWatch,
  IconHeadphones,
  IconKeyboard,
  IconMouse,
  IconPrinter,
  IconRouter,

  // Work & Education
  IconSchool,
  IconBriefcase,
  IconBuilding,
  IconCertificate,
  IconPencil,

  // Insurance & Legal
  IconShield,
  IconLock,
  IconFileText,
  IconFileSpreadsheet,

  // Personal Care
  IconCut,
  IconSpray,

  // Pets
  IconDog,
  IconCat,
  IconPaw,
  IconBone,

  // Family
  IconBabyCarriage,

  // Home Services
  IconHammer,
  IconAxe,
  IconShovel,
  IconPaint,
  IconBrush,

  // Garden
  IconTree,
  IconFlower,
  IconPlant,
  IconGardenCart,

  // Misc
  IconSun,
  IconMoon,
  IconCloud,
  IconUmbrella,
} from '@tabler/icons-react';
import type { IconProps } from '@tabler/icons-react';
import { ThemeIcon, useMantineTheme } from '@mantine/core';

// Map of icon names to Tabler icon components
const iconMap: Record<string, React.ComponentType<IconProps>> = {
  // Finance & Banking (with common aliases)
  payment: IconCreditCard,
  credit_card: IconCreditCard,
  card: IconCreditCard,
  bank: IconBuildingBank,
  account_balance: IconBuildingBank,
  banking: IconBuildingBank,
  wallet: IconWallet,
  account_balance_wallet: IconWallet,
  coin: IconCoin,
  attach_money: IconCoin,
  coins: IconCoin,
  cash: IconCash,
  monetization_on: IconCash,
  money: IconCash,
  savings: IconPigMoney,
  piggy_bank: IconPigMoney,
  loan: IconReportMoney,
  currency_exchange: IconReportMoney,
  investment: IconReportMoney,
  receipt: IconReceipt,
  bill: IconReceipt,
  invoice: IconReceipt,
  dollar: IconCurrencyDollar,
  usd: IconCurrencyDollar,
  euro: IconCurrencyEuro,
  eur: IconCurrencyEuro,
  pound: IconCurrencyPound,
  gbp: IconCurrencyPound,
  yen: IconCurrencyYen,
  yuan: IconCurrencyYen,
  cny: IconCurrencyYen,
  jpy: IconCurrencyYen,

  // Home & Property
  home: IconHome,
  house: IconHome,
  mortgage: IconHome,
  rent: IconHome,
  apartment: IconBuildingSkyscraper,
  condo: IconBuildingSkyscraper,
  building: IconBuildingSkyscraper,
  cottage: IconBuildingCottage,
  cabin: IconBuildingCottage,
  parking: IconParking,
  hoa: IconParking,
  garage: IconBuilding,
  storage: IconBuilding,
  storage_unit: IconBuilding,
  pool: IconPool,
  swimming_pool: IconPool,
  fence: IconFence,
  security_fence: IconFence,
  ladder: IconLadder,
  roofing: IconLadder,

  // Utilities
  electricity: IconBulb,
  lightbulb: IconBulb,
  electric: IconBulb,
  power: IconPlug,
  electrical_services: IconBulb,
  water: IconDroplet,
  water_drop: IconDroplet,
  sewer: IconDroplet,
  gas: IconFlame,
  local_fire_department: IconFlame,
  heating: IconFlame,
  thermostat: IconFlame,
  ac_unit: IconSun,
  internet: IconWifi,
  wifi: IconWifi,
  broadband: IconWifi,
  router: IconRouter,
  modem: IconRouter,
  cable: IconDeviceTv,
  satellite: IconDeviceTv,
  tv: IconDeviceTv,
  streaming: IconMovie,
  trash: IconTrash,
  garbage: IconTrash,
  waste: IconTrash,
  recycle: IconRecycle,
  recycling: IconRecycle,
  plug: IconPlug,
  battery: IconBatteryCharging,
  charging: IconBatteryCharging,
  solar: IconSolarPanel,
  solar_panel: IconSolarPanel,
  solar_power: IconSolarPanel,
  wind: IconWind,
  wind_power: IconWind,

  // Vehicles
  car: IconCar,
  directions_car: IconCar,
  auto: IconCar,
  vehicle: IconCar,
  taxi: IconCar,
  uber: IconCar,
  lyft: IconCar,
  truck: IconTruck,
  pickup: IconTruck,
  delivery: IconTruck,
  rv: IconCaravan,
  camper: IconCaravan,
  caravan: IconCaravan,
  motorhome: IconCaravan,
  motorcycle: IconMotorbike,
  motorbike: IconMotorbike,
  bike_motor: IconMotorbike,
  scooter: IconScooter,
  moped: IconScooter,
  electric_scooter: IconScooter,
  bike: IconBike,
  bicycle: IconBike,
  pedal_bike: IconBike,
  cycling: IconBike,
  bus: IconBus,
  transit: IconBus,
  train: IconBus,
  public_transport: IconBus,
  flight: IconPlane,
  plane: IconPlane,
  airplane: IconPlane,
  travel: IconPlane,
  helicopter: IconHelicopter,
  boat: IconSailboat,
  sailboat: IconSailboat,
  yacht: IconSailboat,
  sailing: IconSailboat,
  kayak: IconKayak,
  canoe: IconKayak,
  paddling: IconKayak,
  fuel: IconGasStation,
  gas_station: IconGasStation,
  local_gas_station: IconGasStation,
  petrol: IconGasStation,
  car_insurance: IconCarCrash,
  auto_insurance: IconCarCrash,
  collision: IconCarCrash,
  car_wash: IconWash,
  wash: IconWash,
  detailing: IconWash,

  // Sports & Youth Activities
  soccer: IconPlayFootball,
  sports_soccer: IconPlayFootball,
  football_soccer: IconPlayFootball,
  football: IconBallFootball,
  american_football: IconBallFootball,
  baseball: IconBallBaseball,
  softball: IconBallBaseball,
  basketball: IconBallBasketball,
  sports_basketball: IconBallBasketball,
  tennis: IconBallTennis,
  sports_tennis: IconBallTennis,
  volleyball: IconBallVolleyball,
  sports_volleyball: IconBallVolleyball,
  bowling: IconBallBowling,
  golf: IconGolf,
  golf_course: IconGolf,
  golfing: IconGolf,
  swimming: IconSwimming,
  swim_lessons: IconSwimming,
  swimming_lessons: IconSwimming,
  ice_skating: IconIceSkating,
  skating: IconIceSkating,
  figure_skating: IconIceSkating,
  skiing: IconSkiJumping,
  ski: IconSkiJumping,
  ski_lessons: IconSkiJumping,
  gymnastics: IconGymnastics,
  tumbling: IconGymnastics,
  running: IconRun,
  track: IconRun,
  cross_country: IconRun,
  hiking: IconRun,
  gym: IconBarbell,
  fitness_center: IconBarbell,
  workout: IconBarbell,
  weights: IconBarbell,
  trophy: IconTrophy,
  championship: IconTrophy,
  competition: IconTrophy,
  medal: IconMedal,
  award: IconAward,
  prize: IconAward,

  // Healthcare & Medical
  healthcare: IconHeartbeat,
  health_insurance: IconHeartbeat,
  medical_services: IconHeartbeat,
  health: IconHeartbeat,
  heart_monitor: IconHeartRateMonitor,
  heart_rate: IconHeartRateMonitor,
  ekg: IconHeartRateMonitor,
  pharmacy: IconPill,
  prescription: IconPill,
  medication: IconPill,
  medicine: IconPill,
  local_pharmacy: IconPill,
  rx: IconPill,
  vaccine: IconVaccine,
  vaccination: IconVaccine,
  shot: IconVaccine,
  immunization: IconVaccine,
  dental: IconDental,
  dentist: IconDental,
  teeth: IconDental,
  orthodontist: IconDental,
  doctor: IconStethoscope,
  physician: IconStethoscope,
  checkup: IconStethoscope,
  clinic: IconStethoscope,
  stethoscope: IconStethoscope,
  ambulance: IconAmbulance,
  emergency: IconAmbulance,
  ems: IconAmbulance,
  first_aid: IconFirstAidKit,
  first_aid_kit: IconFirstAidKit,
  medical_kit: IconFirstAidKit,
  bandage: IconBandage,
  wound_care: IconBandage,
  thermometer: IconThermometer,
  temperature: IconThermometer,
  fever: IconThermometer,
  vision: IconEye,
  eye: IconEye,
  optometry: IconEye,
  eye_exam: IconEye,
  glasses: IconEyeglass,
  eyeglasses: IconEyeglass,
  contacts: IconEyeglass,
  eyewear: IconEyeglass,
  disability: IconDisabled,
  accessible: IconDisabled,
  handicap: IconDisabled,
  mobility: IconDisabled,
  wellness: IconLeaf,
  spa: IconLeaf,
  massage: IconLeaf,
  therapy: IconLeaf,

  // Shopping
  groceries: IconShoppingCart,
  shopping_cart: IconShoppingCart,
  shopping: IconShoppingCart,
  supermarket: IconShoppingCart,
  local_grocery_store: IconShoppingCart,

  // Entertainment & Media
  movie: IconMovie,
  movies: IconMovie,
  cinema: IconMovie,
  netflix: IconMovie,
  hulu: IconMovie,
  disney: IconMovie,
  music: IconMusic,
  spotify: IconMusic,
  apple_music: IconMusic,
  music_note: IconMusic,
  audio: IconMusic,
  gaming: IconDeviceGamepad2,
  videogame_asset: IconDeviceGamepad2,
  games: IconDeviceGamepad2,
  xbox: IconDeviceGamepad2,
  playstation: IconDeviceGamepad2,
  nintendo: IconDeviceGamepad2,
  books: IconBook,
  book: IconBook,
  reading: IconBook,
  kindle: IconBook,
  audible: IconBook,
  backpack: IconBackpack,
  supplies: IconBackpack,
  newspaper: IconNotebook,
  magazine: IconNotebook,
  subscription: IconNotebook,
  gift: IconGift,
  present: IconGift,
  celebration: IconGift,

  // Technology & Devices
  phone: IconPhone,
  smartphone: IconPhone,
  cell_phone: IconPhone,
  mobile_phone: IconPhone,
  iphone: IconPhone,
  android: IconPhone,
  mobile: IconDeviceMobile,
  cell: IconDeviceMobile,
  laptop: IconDeviceLaptop,
  computer: IconDeviceLaptop,
  notebook: IconDeviceLaptop,
  macbook: IconDeviceLaptop,
  desktop: IconDeviceDesktop,
  pc: IconDeviceDesktop,
  workstation: IconDeviceDesktop,
  watch: IconDeviceWatch,
  smartwatch: IconDeviceWatch,
  apple_watch: IconDeviceWatch,
  wearable: IconDeviceWatch,
  headphones: IconHeadphones,
  earbuds: IconHeadphones,
  airpods: IconHeadphones,
  audio_device: IconHeadphones,
  keyboard: IconKeyboard,
  mouse: IconMouse,
  trackpad: IconMouse,
  printer: IconPrinter,
  printing: IconPrinter,
  scanner: IconPrinter,

  // Work & Education
  school: IconSchool,
  tuition: IconSchool,
  education: IconSchool,
  university: IconSchool,
  college: IconSchool,
  student: IconBackpack,
  school_supplies: IconBackpack,
  certificate: IconCertificate,
  certification: IconCertificate,
  diploma: IconCertificate,
  degree: IconCertificate,
  pencil: IconPencil,
  pen: IconPencil,
  writing: IconPencil,
  work: IconBriefcase,
  job: IconBriefcase,
  professional: IconBriefcase,
  career: IconBriefcase,
  business: IconBuilding,
  office: IconBuilding,
  company: IconBuilding,
  corporate: IconBuilding,

  // Insurance & Legal
  insurance: IconShield,
  life_insurance: IconShield,
  home_insurance: IconShield,
  policy: IconShield,
  coverage: IconShield,
  security: IconLock,
  alarm: IconLock,
  security_system: IconLock,
  protection: IconLock,
  lock: IconLock,
  key: IconLock,
  legal: IconFileText,
  attorney: IconFileText,
  lawyer: IconFileText,
  law: IconFileText,
  contract: IconFileText,
  tax: IconFileSpreadsheet,
  taxes: IconFileSpreadsheet,
  accounting: IconFileSpreadsheet,
  accountant: IconFileSpreadsheet,
  bookkeeping: IconFileSpreadsheet,

  // Personal Care & Services
  haircut: IconCut,
  salon: IconSpray,
  barber: IconCut,
  hairstyle: IconCut,
  beauty: IconSpray,
  cosmetics: IconSpray,
  makeup: IconSpray,

  // Pets
  dog: IconDog,
  puppy: IconDog,
  canine: IconDog,
  cat: IconCat,
  kitten: IconCat,
  feline: IconCat,
  pet: IconPaw,
  pets: IconPaw,
  animal: IconPaw,
  vet: IconPaw,
  veterinarian: IconPaw,
  pet_food: IconBone,
  dog_food: IconBone,
  cat_food: IconBone,
  treats: IconBone,

  // Family & Childcare
  childcare: IconBabyCarriage,
  daycare: IconBabyCarriage,
  babysitter: IconBabyCarriage,
  nanny: IconBabyCarriage,
  child_care: IconBabyCarriage,

  // Home Services & Maintenance
  repairs: IconHammer,
  repair: IconHammer,
  handyman: IconHammer,
  maintenance: IconHammer,
  hammer: IconHammer,
  tools: IconHammer,
  toolbox: IconHammer,
  equipment: IconHammer,
  chopping: IconAxe,
  axe: IconAxe,
  tree_service: IconAxe,
  tree_removal: IconAxe,
  digging: IconShovel,
  shovel: IconShovel,
  excavation: IconShovel,
  landscaping: IconShovel,
  painting: IconPaint,
  paint: IconPaint,
  painter: IconPaint,
  brush: IconBrush,
  cleaning: IconBrush,
  cleaner: IconBrush,
  maid: IconBrush,
  housekeeping: IconBrush,

  // Garden & Lawn
  tree: IconTree,
  trees: IconTree,
  landscape: IconTree,
  arborist: IconTree,
  flowers: IconFlower,
  flower: IconFlower,
  floral: IconFlower,
  bouquet: IconFlower,
  plants: IconPlant,
  plant: IconPlant,
  gardening: IconPlant,
  nursery: IconPlant,
  lawn: IconGardenCart,
  lawn_care: IconGardenCart,
  mowing: IconGardenCart,
  yard_work: IconGardenCart,

  // Weather & Misc
  sun: IconSun,
  sunny: IconSun,
  daylight: IconSun,
  moon: IconMoon,
  night: IconMoon,
  lunar: IconMoon,
  evening: IconMoon,
  cloud: IconCloud,
  cloud_storage: IconCloud,
  backup: IconCloud,
  sync: IconCloud,
  umbrella: IconUmbrella,
  umbrella_insurance: IconUmbrella,
  liability: IconUmbrella,
  rain: IconUmbrella,

  // ===== LEGACY FOOD/DRINK ICONS (Migration fallbacks to ShoppingCart) =====
  // These icons were removed but are mapped to ShoppingCart for backward compatibility
  restaurant: IconShoppingCart,
  dining: IconShoppingCart,
  local_dining: IconShoppingCart,
  food: IconShoppingCart,
  pizza: IconShoppingCart,
  local_pizza: IconShoppingCart,
  delivery: IconShoppingCart,
  coffee: IconShoppingCart,
  local_cafe: IconShoppingCart,
  cafe: IconShoppingCart,
  espresso: IconShoppingCart,
  bar: IconShoppingCart,
  pub: IconShoppingCart,
  local_bar: IconShoppingCart,
  wine: IconShoppingCart,
  drinks: IconShoppingCart,
  winery: IconShoppingCart,
  alcohol: IconShoppingCart,
  beer: IconShoppingCart,
  bakery: IconShoppingCart,
  bakery_dining: IconShoppingCart,
  cake: IconShoppingCart,
  sweets: IconShoppingCart,
  dessert: IconShoppingCart,
  bottle: IconShoppingCart,
  beverages: IconShoppingCart,
  local_drink: IconShoppingCart,
  fastfood: IconShoppingCart,
  nightlife: IconShoppingCart,
  glass: IconShoppingCart,
};

interface BillIconProps {
  icon: string;
  size?: number;
  withBackground?: boolean;
}

export function BillIcon({ icon, size = 20, withBackground = false }: BillIconProps) {
  const theme = useMantineTheme();
  const IconComponent = iconMap[icon] || iconMap['payment'] || IconCreditCard;

  if (withBackground) {
    return (
      <ThemeIcon size={size + 12} radius="md" variant="light" color="violet">
        <IconComponent size={size} />
      </ThemeIcon>
    );
  }

  return <IconComponent size={size} color={theme.colors.violet[6]} />;
}

// Export the icon map for the icon picker
// eslint-disable-next-line react-refresh/only-export-components
export const availableIcons = Object.keys(iconMap);
