import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import ts from 'typescript';
import { afterEach, describe, expect, it } from 'vitest';

import {
  checkWebTranslations,
  generateTranslationRegistry,
  syncWebTranslations,
} from './sync-web-translations.mjs';

const temporaryDirectories = [];

async function createFixture() {
  const root = await mkdtemp(path.join(os.tmpdir(), 'billmanager-i18n-'));
  temporaryDirectories.push(root);
  const sourceDirectory = path.join(root, 'web');
  const destinationDirectory = path.join(root, 'mobile', 'locales');
  const registryPath = path.join(root, 'mobile', 'generated.ts');
  await Promise.all([
    mkdir(sourceDirectory, { recursive: true }),
    mkdir(destinationDirectory, { recursive: true }),
  ]);
  return { root, sourceDirectory, destinationDirectory, registryPath };
}

async function writeCatalog(directory, code, languageName, sharedValue = code) {
  await writeFile(
    path.join(directory, `${code}.json`),
    `${JSON.stringify({ _meta: { languageName }, shared: { value: sharedValue } }, null, 2)}\n`,
  );
}

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((directory) => (
    rm(directory, { recursive: true, force: true })
  )));
});

describe('web translation sync', () => {
  it('generates deterministic parseable TypeScript for reserved locale codes', () => {
    // Given
    const locales = [
      { code: 'en', filename: 'en.json', languageName: 'English' },
      { code: 'as', filename: 'as.json', languageName: 'Assamese' },
      { code: 'new', filename: 'new.json', languageName: 'Newari' },
    ];

    // When
    const registry = generateTranslationRegistry(locales);

    // Then
    expect(registry).toBe(`// Generated by npm run i18n:sync. Do not edit.
import locale0 from './locales/en.json';
import locale1 from './locales/as.json';
import locale2 from './locales/new.json';

export const localeCatalogs = {
  'en': locale0,
  'as': locale1,
  'new': locale2,
} as const;

export const LANGUAGE_OPTIONS = [
  { code: 'en', label: 'English' },
  { code: 'as', label: 'Assamese' },
  { code: 'new', label: 'Newari' },
] as const;

export const SUPPORTED_LANGUAGES = [
  'en',
  'as',
  'new',
] as const;
`);
    const compilation = ts.transpileModule(registry, {
      compilerOptions: { module: ts.ModuleKind.ESNext },
      fileName: 'generated.ts',
      reportDiagnostics: true,
    });
    expect(compilation.diagnostics?.filter(({ category }) => category === ts.DiagnosticCategory.Error))
      .toEqual([]);
  });

  it('copies every valid catalog and generates an English-first static Metro registry', async () => {
    // Given
    const fixture = await createFixture();
    await writeCatalog(fixture.sourceDirectory, 'fr', 'Français');
    await writeCatalog(fixture.sourceDirectory, 'de', 'Deutsch');
    await writeCatalog(fixture.sourceDirectory, 'en', 'English');

    // When
    const result = await syncWebTranslations(fixture);

    // Then
    expect(result.languageCodes).toEqual(['en', 'de', 'fr']);
    expect((await readdir(fixture.destinationDirectory)).toSorted())
      .toEqual(['de.json', 'en.json', 'fr.json']);
    expect(await readFile(path.join(fixture.destinationDirectory, 'fr.json'), 'utf8'))
      .toBe(await readFile(path.join(fixture.sourceDirectory, 'fr.json'), 'utf8'));
    const registry = await readFile(fixture.registryPath, 'utf8');
    expect(registry.indexOf("import locale0 from './locales/en.json';"))
      .toBeLessThan(registry.indexOf("import locale1 from './locales/de.json';"));
    expect(registry.indexOf('code: \'de\'')).toBeLessThan(registry.indexOf('code: \'fr\''));
    expect(registry).toContain("{ code: 'fr', label: 'Français' }");
    expect(registry).not.toContain(fixture.root);
    expect(registry).not.toMatch(/generated at|\d{4}-\d{2}-\d{2}/i);
  });

  it('removes stale destination JSON without touching other files or directories', async () => {
    // Given
    const fixture = await createFixture();
    await writeCatalog(fixture.sourceDirectory, 'en', 'English');
    await writeFile(path.join(fixture.destinationDirectory, 'stale.json'), '{}\n');
    await writeFile(path.join(fixture.destinationDirectory, 'notes.txt'), 'keep');
    const nestedDirectory = path.join(fixture.destinationDirectory, 'nested');
    await mkdir(nestedDirectory);
    await writeFile(path.join(nestedDirectory, 'keep.json'), '{}\n');

    // When
    await syncWebTranslations(fixture);

    // Then
    expect((await readdir(fixture.destinationDirectory)).toSorted())
      .toEqual(['en.json', 'nested', 'notes.txt']);
    expect(await readFile(path.join(nestedDirectory, 'keep.json'), 'utf8')).toBe('{}\n');
  });

  it.each([
    ['an invalid locale filename', 'EN', 'English', /lowercase 2-3 letter locale code/],
    ['missing metadata', 'de', undefined, /_meta\.languageName/],
    ['empty metadata', 'de', '   ', /_meta\.languageName/],
  ])('rejects %s', async (_scenario, code, languageName, expectedError) => {
    // Given
    const fixture = await createFixture();
    if (code !== 'EN') await writeCatalog(fixture.sourceDirectory, 'en', 'English');
    if (languageName === undefined) {
      await writeFile(path.join(fixture.sourceDirectory, `${code}.json`), '{"shared":{}}\n');
    } else {
      await writeCatalog(fixture.sourceDirectory, code, languageName);
    }

    // When / Then
    await expect(syncWebTranslations(fixture)).rejects.toThrow(expectedError);
  });

  it('rejects malformed JSON', async () => {
    // Given
    const fixture = await createFixture();
    await writeCatalog(fixture.sourceDirectory, 'en', 'English');
    await writeFile(path.join(fixture.sourceDirectory, 'de.json'), '{invalid');

    // When / Then
    await expect(syncWebTranslations(fixture)).rejects.toThrow(/de\.json contains malformed JSON/);
  });

  it('requires the English catalog', async () => {
    // Given
    const fixture = await createFixture();
    await writeCatalog(fixture.sourceDirectory, 'de', 'Deutsch');

    // When / Then
    await expect(syncWebTranslations(fixture)).rejects.toThrow(/en\.json is required/);
  });

  it('reports generated drift without rewriting files', async () => {
    // Given
    const fixture = await createFixture();
    await writeCatalog(fixture.sourceDirectory, 'en', 'English');
    await syncWebTranslations(fixture);
    await writeFile(fixture.registryPath, 'drifted\n');

    // When / Then
    await expect(checkWebTranslations(fixture)).rejects.toThrow(/generated\.ts/);
    expect(await readFile(fixture.registryPath, 'utf8')).toBe('drifted\n');
  });
});
