export const mobileSettingsResources = {
  en: {
    title: 'Settings',
    tabs: {
      home: 'Home',
      bills: 'Bills',
      calendar: 'Calendar',
      insights: 'Insights',
      settings: 'Settings',
    },
    groups: {
      preferences: 'Preferences',
      security: 'Security',
      connection: 'Connection',
      administration: 'Administration',
      about: 'About',
    },
    home: {
      accountFallback: 'BillManager user',
      accountA11y: 'Account, {{name}}',
      versionLabel: 'BillManager Mobile {{version}}',
      administrator: 'Administrator',
      member: 'Member',
      languageRegion: 'Language & region',
      appearance: 'Appearance',
      billGroups: 'Bill groups',
      billGroupsDetail: 'Manage access and switch defaults',
      security: 'Security & passkeys',
      appLockOn: 'App lock on',
      appLockOff: 'App lock off',
      securityDetail: '2FA and recovery codes',
      linkedAccounts: 'Linked accounts',
      linkedAccountsDetail: 'OAuth and sign-in providers',
      password: 'Password',
      passwordDetail: 'Change your account password',
      selfHosted: 'Self-hosted',
      cloud: 'Cloud',
      development: 'Development',
      verified: 'Connection verified',
      verificationRequired: 'Verification required',
      offlineStorage: 'Offline storage',
      conflicts_one: '{{count}} conflict',
      conflicts_other: '{{count}} conflicts',
      syncing: 'Syncing',
      connected: 'Connected',
      offline: 'Offline',
      users: 'Users',
      usersDetail: 'Roles and account access',
      invitations: 'Invitations',
      invitationsDetail: 'Invite and manage pending members',
      billing: 'Subscription & usage',
      billingDetail: 'Plan, limits, and billing',
      telemetry: 'Privacy & telemetry',
      telemetryDetail: 'Review anonymous usage settings',
      releaseNotes: 'Release notes',
      logOut: 'Log out',
      logOutTitle: 'Log out of BillManager?',
      logOutBody: 'Offline data remains encrypted on this device.',
      cancel: 'Cancel',
    },
    language: {
      title: 'Language & region',
      intro: 'Choose the app language. Amounts and dates continue to follow the active server deployment.',
      appLanguage: 'App language',
      english: 'English',
      german: 'Deutsch',
      regionalFormat: 'Regional format',
      locale: 'Locale',
      currency: 'Currency',
      example: 'Example',
      serverManaged: '{{profile}} controls the currency and regional defaults for this workspace.',
      changeServer: 'Change server profile',
    },
    account: {
      title: 'Account',
      username: 'Username',
      email: 'Email',
      changePassword: 'Change password',
      currentPassword: 'Current password',
      newPassword: 'New password',
      confirmPassword: 'Confirm new password',
      passwordRequirements: 'Use at least 8 characters with uppercase, lowercase, and a number.',
      passwordRequirementsTitle: 'Choose a stronger password',
      passwordMismatchTitle: 'Passwords do not match',
      passwordMismatch: 'Enter the same new password in both fields.',
      incompleteTitle: 'Complete every field',
      incompleteBody: 'Enter your current password and the new password twice.',
      changeFailed: 'Password not changed',
      tryAgain: 'Check your current password and try again.',
      changedTitle: 'Password changed',
      changedBody: 'Your new password is ready to use.',
      saving: 'Saving…',
      linkedSignInTitle: 'Passwordless account',
      linkedSignInBody: 'This account signs in through a linked provider. Manage that connection in Linked accounts.',
    },
    appearance: {
      title: 'Appearance',
      intro: 'Choose how BillManager follows your device appearance.',
      mode: 'Theme',
      light: 'Light',
      dark: 'Dark',
      system: 'System',
      lightDetail: 'Always use the light palette',
      darkDetail: 'Always use the dark palette',
      systemDetail: 'Match your device setting automatically',
      activeSystem: 'Device appearance',
      systemLight: 'Your device is currently using Light.',
      systemDark: 'Your device is currently using Dark.',
    },
    telemetry: {
      title: 'Privacy & telemetry',
      intro: 'Control anonymous instance statistics sent by your active BillManager server.',
      preference: 'Telemetry preference',
      enabled: 'Enabled',
      disabled: 'Disabled',
      undecided: 'Choice required',
      managed: 'Managed by account owner',
      unavailable: 'Unavailable',
      enabledDetail: 'Anonymous instance statistics may be sent.',
      disabledDetail: 'This server will not send anonymous instance statistics.',
      undecidedDetail: 'Confirm whether this server may send anonymous instance statistics.',
      managedDetail: 'Only the account owner can change this server-wide setting.',
      unavailableDetail: 'Connect to the server to read or change this setting.',
      globallyDisabled: 'Telemetry is disabled by this server configuration.',
      keepEnabled: 'Keep telemetry enabled',
      optOut: 'Opt out',
      retry: 'Try again',
      error: 'Could not load the current telemetry preference.',
      collectedTitle: 'Anonymous data includes',
      collected: [
        'Counts of users, bills, and bill groups',
        'Feature usage and server platform information',
        'An anonymous instance identifier and server version',
      ],
      neverTitle: 'Never included',
      never: [
        'Names, email addresses, or account credentials',
        'Bill names, amounts, notes, or financial data',
        'Payment history or payment dates',
      ],
      documentation: 'Read the telemetry documentation',
      saved: 'Telemetry preference updated.',
    },
    releaseNotes: {
      title: 'Release notes',
      intro: 'Version and compatibility details for this installation.',
      currentBuild: 'Current build',
      appVersion: 'App version',
      nativeBuild: 'Native build',
      runtime: 'Runtime',
      channel: 'Update channel',
      server: 'Server version',
      contract: 'Mobile contract',
      development: 'Development',
      unavailable: 'Unavailable',
      latestTitle: 'BillManager Mobile Alpha-1',
      latestStatus: 'Internal native-adaptive testing milestone',
      sections: {
        experience: 'Experience',
        offline: 'Offline & reminders',
        security: 'Security',
      },
      items: {
        experience: [
          'A five-destination phone and tablet interface adapted for iOS and Android',
          'Monthly Pulse home, bill management, calendar, analytics, collaboration, and administration',
        ],
        offline: [
          'Encrypted offline reads and queued bill and payment changes',
          'Local reminders with Open, Snooze, and Mark Paid actions',
        ],
        security: [
          'Biometric app lock, passkeys, recovery codes, and isolated server profiles',
          'Production self-hosted connections require trusted HTTPS',
        ],
      },
      serverProfiles: 'Manage server profiles',
    },
  },
  de: {
    title: 'Einstellungen',
    tabs: {
      home: 'Start',
      bills: 'Rechnungen',
      calendar: 'Kalender',
      insights: 'Analysen',
      settings: 'Einstellungen',
    },
    groups: {
      preferences: 'Einstellungen',
      security: 'Sicherheit',
      connection: 'Verbindung',
      administration: 'Verwaltung',
      about: 'Info',
    },
    home: {
      accountFallback: 'BillManager-Nutzer',
      accountA11y: 'Konto, {{name}}',
      versionLabel: 'BillManager Mobile {{version}}',
      administrator: 'Administrator',
      member: 'Mitglied',
      languageRegion: 'Sprache & Region',
      appearance: 'Darstellung',
      billGroups: 'Rechnungsgruppen',
      billGroupsDetail: 'Zugriff verwalten und Standard wechseln',
      security: 'Sicherheit & Passkeys',
      appLockOn: 'App-Sperre aktiv',
      appLockOff: 'App-Sperre inaktiv',
      securityDetail: '2FA und Wiederherstellungscodes',
      linkedAccounts: 'Verknüpfte Konten',
      linkedAccountsDetail: 'OAuth- und Anmeldeanbieter',
      password: 'Passwort',
      passwordDetail: 'Kontopasswort ändern',
      selfHosted: 'Selbst gehostet',
      cloud: 'Cloud',
      development: 'Entwicklung',
      verified: 'Verbindung bestätigt',
      verificationRequired: 'Bestätigung erforderlich',
      offlineStorage: 'Offline-Speicher',
      conflicts_one: '{{count}} Konflikt',
      conflicts_other: '{{count}} Konflikte',
      syncing: 'Synchronisierung',
      connected: 'Verbunden',
      offline: 'Offline',
      users: 'Nutzer',
      usersDetail: 'Rollen und Kontozugriff',
      invitations: 'Einladungen',
      invitationsDetail: 'Ausstehende Mitglieder einladen und verwalten',
      billing: 'Abonnement & Nutzung',
      billingDetail: 'Tarif, Limits und Abrechnung',
      telemetry: 'Datenschutz & Telemetrie',
      telemetryDetail: 'Anonyme Nutzungsdaten verwalten',
      releaseNotes: 'Versionshinweise',
      logOut: 'Abmelden',
      logOutTitle: 'Von BillManager abmelden?',
      logOutBody: 'Offline-Daten bleiben auf diesem Gerät verschlüsselt.',
      cancel: 'Abbrechen',
    },
    language: {
      title: 'Sprache & Region',
      intro: 'Wählen Sie die App-Sprache. Beträge und Datumsangaben folgen weiterhin der aktiven Serverbereitstellung.',
      appLanguage: 'App-Sprache',
      english: 'English',
      german: 'Deutsch',
      regionalFormat: 'Regionale Formatierung',
      locale: 'Gebietsschema',
      currency: 'Währung',
      example: 'Beispiel',
      serverManaged: '{{profile}} legt Währung und regionale Standards für diesen Arbeitsbereich fest.',
      changeServer: 'Serverprofil wechseln',
    },
    account: {
      title: 'Konto',
      username: 'Nutzername',
      email: 'E-Mail',
      changePassword: 'Passwort ändern',
      currentPassword: 'Aktuelles Passwort',
      newPassword: 'Neues Passwort',
      confirmPassword: 'Neues Passwort bestätigen',
      passwordRequirements: 'Verwenden Sie mindestens 8 Zeichen mit Groß- und Kleinbuchstaben sowie einer Zahl.',
      passwordRequirementsTitle: 'Stärkeres Passwort wählen',
      passwordMismatchTitle: 'Passwörter stimmen nicht überein',
      passwordMismatch: 'Geben Sie in beiden Feldern dasselbe neue Passwort ein.',
      incompleteTitle: 'Alle Felder ausfüllen',
      incompleteBody: 'Geben Sie das aktuelle Passwort und das neue Passwort zweimal ein.',
      changeFailed: 'Passwort nicht geändert',
      tryAgain: 'Prüfen Sie das aktuelle Passwort und versuchen Sie es erneut.',
      changedTitle: 'Passwort geändert',
      changedBody: 'Ihr neues Passwort kann jetzt verwendet werden.',
      saving: 'Speichern…',
      linkedSignInTitle: 'Passwortloses Konto',
      linkedSignInBody: 'Dieses Konto meldet sich über einen verknüpften Anbieter an. Verwalten Sie die Verbindung unter Verknüpfte Konten.',
    },
    appearance: {
      title: 'Darstellung',
      intro: 'Legen Sie fest, wie BillManager der Darstellung Ihres Geräts folgt.',
      mode: 'Design',
      light: 'Hell',
      dark: 'Dunkel',
      system: 'System',
      lightDetail: 'Immer das helle Farbschema verwenden',
      darkDetail: 'Immer das dunkle Farbschema verwenden',
      systemDetail: 'Automatisch der Geräteeinstellung folgen',
      activeSystem: 'Gerätedarstellung',
      systemLight: 'Ihr Gerät verwendet derzeit das helle Design.',
      systemDark: 'Ihr Gerät verwendet derzeit das dunkle Design.',
    },
    telemetry: {
      title: 'Datenschutz & Telemetrie',
      intro: 'Verwalten Sie anonyme Instanzstatistiken des aktiven BillManager-Servers.',
      preference: 'Telemetrieeinstellung',
      enabled: 'Aktiviert',
      disabled: 'Deaktiviert',
      undecided: 'Auswahl erforderlich',
      managed: 'Vom Kontoinhaber verwaltet',
      unavailable: 'Nicht verfügbar',
      enabledDetail: 'Anonyme Instanzstatistiken dürfen gesendet werden.',
      disabledDetail: 'Dieser Server sendet keine anonymen Instanzstatistiken.',
      undecidedDetail: 'Bestätigen Sie, ob dieser Server anonyme Instanzstatistiken senden darf.',
      managedDetail: 'Nur der Kontoinhaber kann diese serverweite Einstellung ändern.',
      unavailableDetail: 'Stellen Sie eine Verbindung her, um diese Einstellung zu lesen oder zu ändern.',
      globallyDisabled: 'Die Telemetrie ist in der Serverkonfiguration deaktiviert.',
      keepEnabled: 'Telemetrie aktiviert lassen',
      optOut: 'Ablehnen',
      retry: 'Erneut versuchen',
      error: 'Die aktuelle Telemetrieeinstellung konnte nicht geladen werden.',
      collectedTitle: 'Anonyme Daten umfassen',
      collected: [
        'Anzahl von Nutzern, Rechnungen und Rechnungsgruppen',
        'Funktionsnutzung und Plattforminformationen des Servers',
        'Eine anonyme Instanz-ID und die Serverversion',
      ],
      neverTitle: 'Niemals enthalten',
      never: [
        'Namen, E-Mail-Adressen oder Anmeldedaten',
        'Rechnungsnamen, Beträge, Notizen oder Finanzdaten',
        'Zahlungsverlauf oder Zahlungsdaten',
      ],
      documentation: 'Telemetriedokumentation lesen',
      saved: 'Telemetrieeinstellung aktualisiert.',
    },
    releaseNotes: {
      title: 'Versionshinweise',
      intro: 'Versions- und Kompatibilitätsdetails dieser Installation.',
      currentBuild: 'Aktueller Build',
      appVersion: 'App-Version',
      nativeBuild: 'Nativer Build',
      runtime: 'Laufzeit',
      channel: 'Update-Kanal',
      server: 'Serverversion',
      contract: 'Mobile-Vertrag',
      development: 'Entwicklung',
      unavailable: 'Nicht verfügbar',
      latestTitle: 'BillManager Mobile Alpha-1',
      latestStatus: 'Interner Meilenstein für native-adaptive Tests',
      sections: {
        experience: 'Bedienung',
        offline: 'Offline & Erinnerungen',
        security: 'Sicherheit',
      },
      items: {
        experience: [
          'Eine Oberfläche mit fünf Bereichen für Smartphones und Tablets, angepasst an iOS und Android',
          'Monatsübersicht, Rechnungen, Kalender, Analysen, Zusammenarbeit und Verwaltung',
        ],
        offline: [
          'Verschlüsselte Offline-Daten und eine Warteschlange für Rechnungs- und Zahlungsänderungen',
          'Lokale Erinnerungen mit Öffnen, Später erinnern und Als bezahlt markieren',
        ],
        security: [
          'Biometrische App-Sperre, Passkeys, Wiederherstellungscodes und getrennte Serverprofile',
          'Produktive selbst gehostete Verbindungen erfordern vertrauenswürdiges HTTPS',
        ],
      },
      serverProfiles: 'Serverprofile verwalten',
    },
  },
} as const;
