export const authSecurityResources = {
  en: {
    auth: {
      common: {
        username: 'Username',
        password: 'Password',
        email: 'Email',
        confirmPassword: 'Confirm password',
        cancel: 'Cancel',
        tryAgain: 'Try again',
        backToSignIn: 'Back to sign in',
        requestNewLink: 'Request a new link',
        sixDigitCode: 'Six-digit code',
        recoveryCode: 'Recovery code',
        passwordHint: 'At least 8 characters with uppercase, lowercase, and a number',
      },
      validation: {
        email: 'Enter a valid email address',
        usernameMin: 'Username must be at least 3 characters',
        usernameMax: 'Username must be 32 characters or less',
        usernameCharacters: 'Use letters, numbers, underscores, or hyphens; start and end with a letter or number',
        passwordMin: 'Password must be at least 8 characters',
        passwordMax: 'Password must be 128 characters or less',
        passwordUppercase: 'Password must contain an uppercase letter',
        passwordLowercase: 'Password must contain a lowercase letter',
        passwordNumber: 'Password must contain a number',
        usernameRequired: 'Enter your username',
        passwordRequired: 'Enter your password',
        passwordsMismatch: 'Passwords do not match',
        code: 'Enter the six-digit code',
        recoveryCode: 'Enter a recovery code',
      },
      login: {
        title: 'Sign in',
        subtitle: 'Continue to {{server}}',
        createAccount: 'Create an account',
        signIn: 'Sign in',
        forgotPassword: 'Forgot password?',
        connectedAccount: 'Use a connected account',
        changeServer: 'Change server',
        incompleteTitle: 'Sign-in incomplete',
      },
      register: {
        title: 'Create an account',
        unavailable: 'Account registration is disabled for this BillManager server. Ask an administrator for an invitation.',
        subtitle: 'Your first bill group is created automatically.',
        back: 'Back to sign in',
        usernameHint: '3–32 characters; letters, numbers, underscores, and hyphens',
        submit: 'Create account',
        failed: 'Account creation failed',
      },
      emailRequest: {
        resetTitle: 'Reset password',
        resendTitle: 'Resend verification',
        unavailable: 'Email delivery is not configured for this BillManager server. Contact its administrator for help.',
        resetHeading: 'Reset your password',
        resetSubtitle: 'We will send reset instructions if the address is registered.',
        resendSubtitle: 'We will send a fresh link if the address still needs verification.',
        resetSuccess: 'If the address is registered, a password reset link has been sent.',
        resendSuccess: 'If the address is unverified, a new verification link has been sent.',
        requestFailed: 'Request failed',
        sendReset: 'Send reset link',
        sendVerification: 'Send verification link',
      },
      passwordCompletion: {
        linkUnavailable: 'Link unavailable',
        linkMissing: 'This password link is missing or incomplete.',
        resetTitle: 'Choose a new password',
        forcedTitle: 'Update your password',
        forcedSubtitle: 'Your administrator requires a new password before you continue.',
        resetSubtitle: 'All existing sessions will be signed out after this change.',
        requirements: 'Use at least 8 characters with an uppercase letter, a lowercase letter, and a number.',
        updateFailed: 'Password could not be updated',
        updated: 'Your password has been updated securely.',
        reset: 'Reset password',
        save: 'Save and continue',
      },
      teamInvite: {
        incomplete: 'This invitation link is incomplete.',
        invalid: 'This invitation is invalid or expired.',
        acceptFailed: 'The invitation could not be accepted.',
        title: 'Join BillManager',
        subtitle: '{{inviter}} invited {{email}}',
        review: 'Review your invitation',
        loading: 'Loading invitation',
        existingAccount: 'Already have an account? Sign in',
        submit: 'Create account and join',
      },
      shareInvite: {
        incomplete: 'This share link is incomplete.',
        invalid: 'This share invitation is invalid or expired.',
        unavailableTitle: 'Shared bill invitation',
        unavailable: 'Bill sharing is not supported by this BillManager server.',
        title: 'Shared bill invitation',
        subtitle: 'Confirm the bill before adding it to your account',
        loading: 'Loading shared bill',
        sharedBy: 'Shared by {{owner}} for {{email}}',
        sharedByOwner: 'Shared by {{owner}}',
        portion: 'Your portion: {{amount}}',
        accept: 'Accept shared bill',
        signIn: 'Sign in to accept',
        createAccount: 'Create an account',
        acceptFailed: 'The invitation could not be accepted.',
      },
      oauth: {
        linkTitle: 'Link an account',
        signInTitle: 'Use a connected account',
        unavailable: 'No OAuth or OIDC providers are enabled on this BillManager server.',
        subtitle: 'Authorization opens in your system browser. BillManager never sees your provider password.',
        loading: 'Loading providers',
        loadFailed: 'Connected account providers could not be loaded.',
        connectFailed: 'Could not connect to {{provider}}.',
        passwordChangeRequired: 'Sign in with your password first to complete the required password change.',
        cancel: 'Cancel',
        linkProvider: 'Link {{provider}}',
        continueProvider: 'Continue with {{provider}}',
        noneAvailable: 'The configured providers are not currently available.',
        callbackMissing: 'The authorization callback is missing required information.',
        completing: 'Completing sign in',
        verifying: 'Verifying authorization',
      },
      verification: {
        title: 'Verify your email',
        subtitle: 'This link can only be used once.',
        unavailableTitle: 'Verify email',
        unavailable: 'Email verification is not enabled on this BillManager server.',
        missingTitle: 'Verification link unavailable',
        missing: 'The verification link is missing its token.',
        success: 'Your email is verified. You can now sign in.',
        invalid: 'The verification link is invalid.',
        verifying: 'Verifying your email',
        continue: 'Continue to sign in',
      },
      twoFactor: {
        title: 'Verify it’s you',
        subtitle: 'Choose one of the security methods configured for your account.',
        cancel: 'Cancel sign in',
        email: 'Email code',
        passkey: 'Passkey',
        recovery: 'Recovery code',
        verificationFailed: 'Verification failed.',
        codeSent: 'A verification code was sent.',
        codeSendFailed: 'The verification code could not be sent.',
        nativeUnavailable: 'This build cannot complete a native passkey ceremony.',
        optionsFailed: 'Passkey options could not be loaded.',
        passkeyCancelled: 'Passkey verification was cancelled.',
        sendEmail: 'Send email code',
        verifyCode: 'Verify code',
        passkeyBuildUnavailable: 'Passkey sign-in is unavailable in this build. Choose another method for now.',
        usePasskey: 'Use passkey',
        useRecovery: 'Use recovery code',
        noMethods: 'No supported verification methods are available.',
      },
      navigation: {
        serverConnections: 'Server connections',
      },
    },
    security: {
      common: {
        on: 'On',
        off: 'Off',
        enabled: 'Enabled',
        notEnabled: 'Not enabled',
        cancel: 'Cancel',
        refresh: 'Refresh',
        password: 'Password',
        emailConfirmationCode: 'Email confirmation code',
        sendEmailConfirmationCode: 'Send email confirmation code',
        confirmationSent: 'A confirmation code was sent.',
        confirmationFailed: 'A confirmation code could not be sent.',
        sixDigitCode: 'Six-digit code',
      },
      overview: {
        title: 'Security',
        subtitle: 'Manage sign-in methods and protect access to your financial information.',
        device: 'This device',
        biometric: 'Biometric app lock',
        biometricManaged: 'Biometric app lock is managed by this build’s device settings.',
        signIn: 'Sign-in security',
        twoFactor: 'Two-factor authentication',
        methods: 'Email codes, passkeys, and recovery codes',
        serverDisabled: 'Not enabled by this server',
        linkedAccounts: 'Linked accounts',
        providers: 'Manage OAuth and OIDC providers',
        noProviders: 'No providers configured',
        accountData: 'Account data',
        accountDataDescription: 'Account deletion permanently removes every user, bill group, bill, and payment owned by this account.',
        deleteAccount: 'Delete BillManager account',
      },
      linked: {
        title: 'Linked accounts',
        unavailable: 'No OAuth or OIDC providers are enabled on this BillManager server.',
        subtitle: 'Use trusted identity providers to sign in without sharing provider passwords with BillManager.',
        loading: 'Loading linked accounts',
        loadFailed: 'Linked accounts could not be loaded.',
        connected: 'Connected providers',
        empty: 'No connected accounts yet.',
        emailMissing: 'Email not provided',
        unlinkTitle: 'Unlink {{provider}}?',
        unlinkWarning: 'You may be unable to sign in if this is your only login method.',
        unlink: 'Unlink',
        unlinkFailed: 'The account could not be unlinked.',
        unlinked: '{{provider}} was unlinked.',
        add: 'Link another account',
      },
      twoFactorSettings: {
        title: 'Two-factor authentication',
        unavailable: 'Two-factor authentication is not enabled on this BillManager server.',
        enabledSubtitle: 'Your account requires an additional verification method at sign in.',
        disabledSubtitle: 'Add a second verification method to protect your account.',
        loading: 'Loading security status',
        loadFailed: 'Two-factor status could not be loaded.',
        enabledNotice: 'Two-factor authentication is on.',
        disabledNotice: 'Two-factor authentication is off.',
        methods: 'Verification methods',
        emailCodes: 'Email one-time codes',
        passkeys: 'Passkeys',
        registered_one: '{{count}} registered',
        registered_other: '{{count}} registered',
        recoveryCodes: 'Recovery codes',
        available: 'Available',
        generate: 'Generate codes',
        turnOff: 'Turn off two-factor authentication',
        disableAll: 'Disable all methods',
      },
      recovery: {
        panelTitle: 'Save these recovery codes',
        panelDescription: 'They are shown once. Each code can be used one time if your other methods are unavailable.',
        accessibility: 'Recovery codes: {{codes}}',
        shareTitle: 'BillManager recovery codes',
        shareMessage: 'BillManager recovery codes\n\n{{codes}}\n\nEach code can be used once. Store them securely.',
        share: 'Share or save securely',
        title: 'Recovery codes',
        subtitle: 'Use one if you cannot access your email or passkey.',
        regenerateTitle: 'Generate new recovery codes?',
        regenerateWarning: 'Every existing recovery code will stop working immediately.',
        generate: 'Generate',
        failed: 'Recovery codes could not be generated.',
        warning: 'Generating a new set invalidates every previous recovery code.',
        generateNew: 'Generate new codes',
      },
      emailSetup: {
        title: 'Email one-time codes',
        unavailable: 'Email one-time codes are not enabled on this BillManager server.',
        subtitle: 'We will verify that security codes can reach the email address on your account.',
        sendFailed: 'A setup code could not be sent.',
        verifyFailed: 'The code could not be verified.',
        send: 'Send setup code',
        verify: 'Verify and enable',
        resend: 'Send a new code',
      },
      passkeys: {
        title: 'Passkeys',
        unavailable: 'Passkeys are not enabled on this BillManager server.',
        subtitle: 'Passkeys use your device screen lock or security key instead of a typed code.',
        defaultDevice: 'My device',
        nameRequired: 'Enter a name for this passkey',
        confirmationRequired: 'Enter your password or confirmation code',
        loading: 'Loading passkeys',
        loadFailed: 'Passkeys could not be loaded.',
        nativeUnavailable: 'This build does not include the native passkey credential adapter.',
        optionsFailed: 'Registration options could not be loaded.',
        registrationFailed: 'The passkey could not be registered.',
        registrationCancelled: 'Passkey registration was cancelled.',
        removed: 'Passkey removed.',
        removeFailed: 'The passkey could not be removed.',
        addSection: 'Add a passkey',
        name: 'Passkey name',
        nameHint: 'For example, Personal iPhone',
        create: 'Create passkey',
        registeredSection: 'Registered passkeys',
        empty: 'No passkeys registered.',
        lastUsed: 'Last used {{date}}',
        neverUsed: 'Never used',
        removeTitle: 'Remove {{name}}?',
        removeDescription: 'Confirm this security-sensitive change.',
        remove: 'Remove passkey',
      },
      disableTwoFactor: {
        title: 'Disable two-factor authentication',
        subtitle: 'This removes every configured second factor from your account.',
        warning: 'You will sign in with only your password or linked account after this change.',
        confirmTitle: 'Disable two-factor authentication?',
        confirmWarning: 'All passkeys and recovery codes will be removed from this account.',
        disable: 'Disable',
        failed: 'Two-factor authentication could not be disabled.',
        success: 'Two-factor authentication is off.',
        action: 'Disable two-factor authentication',
      },
      deleteAccount: {
        title: 'Delete account',
        unavailable: 'Only the account owner can permanently delete this BillManager account.',
        subtitle: 'This action permanently removes the entire account and all data it owns.',
        irreversibleTitle: 'This cannot be undone',
        irreversible: 'Export anything you need before continuing. Other users in this account will also lose access.',
        typeDelete: 'Type DELETE to confirm',
        typeDeleteError: 'Type DELETE exactly',
        passwordRequired: 'Enter your password',
        confirmTitle: 'Permanently delete this account?',
        confirmWarning: 'Every owned user, bill group, bill, payment, share, and subscription record will be removed. This cannot be undone.',
        deletePermanently: 'Delete permanently',
        failed: 'The account could not be deleted.',
        action: 'Delete account permanently',
      },
      biometric: {
        title: 'BillManager is locked',
        subtitle: 'Unlock to view your bills and payment information.',
        enrollmentChanged: 'Your biometric enrollment changed. Verify your account password once to protect the new enrollment.',
        notEnrolled: 'Set up biometrics or a device passcode in system settings, then try again.',
        verificationFailed: 'BillManager could not verify your identity.',
        passwordRequired: 'Enter your BillManager password.',
        passwordFailed: 'BillManager could not verify your password.',
        setupBiometrics: 'Set up biometrics in system settings, then try again.',
        passwordLabel: 'BillManager password',
        verifyAccountPassword: 'Verify account password',
        unlockApp: 'Unlock BillManager',
        verifying: 'Verifying…',
        signOut: 'Sign out to verify identity',
        verifyPassword: 'Verify password',
        unlock: 'Unlock',
        reauthHelp: 'After verification, BillManager binds app lock to the newly enrolled biometrics.',
      },
    },
  },
  de: {
    auth: {
      common: {
        username: 'Nutzername',
        password: 'Passwort',
        email: 'E-Mail',
        confirmPassword: 'Passwort bestätigen',
        cancel: 'Abbrechen',
        tryAgain: 'Erneut versuchen',
        backToSignIn: 'Zurück zur Anmeldung',
        requestNewLink: 'Neuen Link anfordern',
        sixDigitCode: 'Sechsstelliger Code',
        recoveryCode: 'Wiederherstellungscode',
        passwordHint: 'Mindestens 8 Zeichen mit Großbuchstaben, Kleinbuchstaben und einer Zahl',
      },
      validation: {
        email: 'Geben Sie eine gültige E-Mail-Adresse ein',
        usernameMin: 'Der Nutzername muss mindestens 3 Zeichen lang sein',
        usernameMax: 'Der Nutzername darf höchstens 32 Zeichen lang sein',
        usernameCharacters: 'Verwenden Sie Buchstaben, Zahlen, Unterstriche oder Bindestriche; beginnen und enden Sie mit einem Buchstaben oder einer Zahl',
        passwordMin: 'Das Passwort muss mindestens 8 Zeichen lang sein',
        passwordMax: 'Das Passwort darf höchstens 128 Zeichen lang sein',
        passwordUppercase: 'Das Passwort muss einen Großbuchstaben enthalten',
        passwordLowercase: 'Das Passwort muss einen Kleinbuchstaben enthalten',
        passwordNumber: 'Das Passwort muss eine Zahl enthalten',
        usernameRequired: 'Geben Sie Ihren Nutzernamen ein',
        passwordRequired: 'Geben Sie Ihr Passwort ein',
        passwordsMismatch: 'Die Passwörter stimmen nicht überein',
        code: 'Geben Sie den sechsstelligen Code ein',
        recoveryCode: 'Geben Sie einen Wiederherstellungscode ein',
      },
      login: {
        title: 'Anmelden',
        subtitle: 'Weiter zu {{server}}',
        createAccount: 'Konto erstellen',
        signIn: 'Anmelden',
        forgotPassword: 'Passwort vergessen?',
        connectedAccount: 'Verknüpftes Konto verwenden',
        changeServer: 'Server wechseln',
        incompleteTitle: 'Anmeldung unvollständig',
      },
      register: {
        title: 'Konto erstellen',
        unavailable: 'Die Kontoregistrierung ist auf diesem BillManager-Server deaktiviert. Bitten Sie einen Administrator um eine Einladung.',
        subtitle: 'Ihre erste Rechnungsgruppe wird automatisch erstellt.',
        back: 'Zurück zur Anmeldung',
        usernameHint: '3–32 Zeichen; Buchstaben, Zahlen, Unterstriche und Bindestriche',
        submit: 'Konto erstellen',
        failed: 'Konto konnte nicht erstellt werden',
      },
      emailRequest: {
        resetTitle: 'Passwort zurücksetzen',
        resendTitle: 'Bestätigung erneut senden',
        unavailable: 'Der E-Mail-Versand ist auf diesem BillManager-Server nicht eingerichtet. Wenden Sie sich an den Administrator.',
        resetHeading: 'Passwort zurücksetzen',
        resetSubtitle: 'Wenn die Adresse registriert ist, senden wir Anweisungen zum Zurücksetzen.',
        resendSubtitle: 'Wenn die Adresse noch bestätigt werden muss, senden wir einen neuen Link.',
        resetSuccess: 'Wenn die Adresse registriert ist, wurde ein Link zum Zurücksetzen gesendet.',
        resendSuccess: 'Wenn die Adresse unbestätigt ist, wurde ein neuer Bestätigungslink gesendet.',
        requestFailed: 'Anfrage fehlgeschlagen',
        sendReset: 'Link zum Zurücksetzen senden',
        sendVerification: 'Bestätigungslink senden',
      },
      passwordCompletion: {
        linkUnavailable: 'Link nicht verfügbar',
        linkMissing: 'Dieser Passwort-Link fehlt oder ist unvollständig.',
        resetTitle: 'Neues Passwort wählen',
        forcedTitle: 'Passwort aktualisieren',
        forcedSubtitle: 'Ihr Administrator verlangt ein neues Passwort, bevor Sie fortfahren.',
        resetSubtitle: 'Nach dieser Änderung werden alle bestehenden Sitzungen abgemeldet.',
        requirements: 'Verwenden Sie mindestens 8 Zeichen mit einem Großbuchstaben, einem Kleinbuchstaben und einer Zahl.',
        updateFailed: 'Passwort konnte nicht aktualisiert werden',
        updated: 'Ihr Passwort wurde sicher aktualisiert.',
        reset: 'Passwort zurücksetzen',
        save: 'Speichern und fortfahren',
      },
      teamInvite: {
        incomplete: 'Dieser Einladungslink ist unvollständig.',
        invalid: 'Diese Einladung ist ungültig oder abgelaufen.',
        acceptFailed: 'Die Einladung konnte nicht angenommen werden.',
        title: 'BillManager beitreten',
        subtitle: '{{inviter}} hat {{email}} eingeladen',
        review: 'Einladung prüfen',
        loading: 'Einladung wird geladen',
        existingAccount: 'Sie haben bereits ein Konto? Anmelden',
        submit: 'Konto erstellen und beitreten',
      },
      shareInvite: {
        incomplete: 'Dieser Freigabelink ist unvollständig.',
        invalid: 'Diese Freigabeeinladung ist ungültig oder abgelaufen.',
        unavailableTitle: 'Einladung zu einer geteilten Rechnung',
        unavailable: 'Das Teilen von Rechnungen wird von diesem BillManager-Server nicht unterstützt.',
        title: 'Einladung zu einer geteilten Rechnung',
        subtitle: 'Prüfen Sie die Rechnung, bevor Sie sie Ihrem Konto hinzufügen',
        loading: 'Geteilte Rechnung wird geladen',
        sharedBy: 'Geteilt von {{owner}} für {{email}}',
        sharedByOwner: 'Geteilt von {{owner}}',
        portion: 'Ihr Anteil: {{amount}}',
        accept: 'Geteilte Rechnung annehmen',
        signIn: 'Zum Annehmen anmelden',
        createAccount: 'Konto erstellen',
        acceptFailed: 'Die Einladung konnte nicht angenommen werden.',
      },
      oauth: {
        linkTitle: 'Konto verknüpfen',
        signInTitle: 'Verknüpftes Konto verwenden',
        unavailable: 'Auf diesem BillManager-Server sind keine OAuth- oder OIDC-Anbieter aktiviert.',
        subtitle: 'Die Autorisierung wird im Systembrowser geöffnet. BillManager sieht Ihr Anbieterpasswort niemals.',
        loading: 'Anbieter werden geladen',
        loadFailed: 'Anbieter für verknüpfte Konten konnten nicht geladen werden.',
        connectFailed: 'Verbindung mit {{provider}} nicht möglich.',
        passwordChangeRequired: 'Melden Sie sich zuerst mit Ihrem Passwort an, um die erforderliche Passwortänderung abzuschließen.',
        cancel: 'Abbrechen',
        linkProvider: '{{provider}} verknüpfen',
        continueProvider: 'Weiter mit {{provider}}',
        noneAvailable: 'Die konfigurierten Anbieter sind derzeit nicht verfügbar.',
        callbackMissing: 'Im Autorisierungsrückruf fehlen erforderliche Informationen.',
        completing: 'Anmeldung wird abgeschlossen',
        verifying: 'Autorisierung wird geprüft',
      },
      verification: {
        title: 'E-Mail-Adresse bestätigen',
        subtitle: 'Dieser Link kann nur einmal verwendet werden.',
        unavailableTitle: 'E-Mail bestätigen',
        unavailable: 'Die E-Mail-Bestätigung ist auf diesem BillManager-Server nicht aktiviert.',
        missingTitle: 'Bestätigungslink nicht verfügbar',
        missing: 'Im Bestätigungslink fehlt das Token.',
        success: 'Ihre E-Mail-Adresse ist bestätigt. Sie können sich jetzt anmelden.',
        invalid: 'Der Bestätigungslink ist ungültig.',
        verifying: 'E-Mail-Adresse wird bestätigt',
        continue: 'Weiter zur Anmeldung',
      },
      twoFactor: {
        title: 'Identität bestätigen',
        subtitle: 'Wählen Sie eine der für Ihr Konto eingerichteten Sicherheitsmethoden.',
        cancel: 'Anmeldung abbrechen',
        email: 'E-Mail-Code',
        passkey: 'Passkey',
        recovery: 'Wiederherstellungscode',
        verificationFailed: 'Bestätigung fehlgeschlagen.',
        codeSent: 'Ein Bestätigungscode wurde gesendet.',
        codeSendFailed: 'Der Bestätigungscode konnte nicht gesendet werden.',
        nativeUnavailable: 'Dieser Build kann keine native Passkey-Anmeldung durchführen.',
        optionsFailed: 'Passkey-Optionen konnten nicht geladen werden.',
        passkeyCancelled: 'Passkey-Bestätigung wurde abgebrochen.',
        sendEmail: 'E-Mail-Code senden',
        verifyCode: 'Code bestätigen',
        passkeyBuildUnavailable: 'Die Passkey-Anmeldung ist in diesem Build nicht verfügbar. Wählen Sie vorerst eine andere Methode.',
        usePasskey: 'Passkey verwenden',
        useRecovery: 'Wiederherstellungscode verwenden',
        noMethods: 'Keine unterstützten Bestätigungsmethoden verfügbar.',
      },
      navigation: {
        serverConnections: 'Serververbindungen',
      },
    },
    security: {
      common: {
        on: 'Ein',
        off: 'Aus',
        enabled: 'Aktiviert',
        notEnabled: 'Nicht aktiviert',
        cancel: 'Abbrechen',
        refresh: 'Aktualisieren',
        password: 'Passwort',
        emailConfirmationCode: 'E-Mail-Bestätigungscode',
        sendEmailConfirmationCode: 'E-Mail-Bestätigungscode senden',
        confirmationSent: 'Ein Bestätigungscode wurde gesendet.',
        confirmationFailed: 'Ein Bestätigungscode konnte nicht gesendet werden.',
        sixDigitCode: 'Sechsstelliger Code',
      },
      overview: {
        title: 'Sicherheit',
        subtitle: 'Verwalten Sie Anmeldemethoden und schützen Sie den Zugriff auf Ihre Finanzdaten.',
        device: 'Dieses Gerät',
        biometric: 'Biometrische App-Sperre',
        biometricManaged: 'Die biometrische App-Sperre wird über die Geräteeinstellungen dieses Builds verwaltet.',
        signIn: 'Anmeldesicherheit',
        twoFactor: 'Zwei-Faktor-Authentifizierung',
        methods: 'E-Mail-Codes, Passkeys und Wiederherstellungscodes',
        serverDisabled: 'Von diesem Server nicht aktiviert',
        linkedAccounts: 'Verknüpfte Konten',
        providers: 'OAuth- und OIDC-Anbieter verwalten',
        noProviders: 'Keine Anbieter konfiguriert',
        accountData: 'Kontodaten',
        accountDataDescription: 'Beim Löschen des Kontos werden alle Nutzer, Rechnungsgruppen, Rechnungen und Zahlungen dieses Kontos dauerhaft entfernt.',
        deleteAccount: 'BillManager-Konto löschen',
      },
      linked: {
        title: 'Verknüpfte Konten',
        unavailable: 'Auf diesem BillManager-Server sind keine OAuth- oder OIDC-Anbieter aktiviert.',
        subtitle: 'Verwenden Sie vertrauenswürdige Identitätsanbieter, ohne Anbieterpasswörter mit BillManager zu teilen.',
        loading: 'Verknüpfte Konten werden geladen',
        loadFailed: 'Verknüpfte Konten konnten nicht geladen werden.',
        connected: 'Verbundene Anbieter',
        empty: 'Noch keine verbundenen Konten.',
        emailMissing: 'Keine E-Mail-Adresse angegeben',
        unlinkTitle: '{{provider}} trennen?',
        unlinkWarning: 'Wenn dies Ihre einzige Anmeldemethode ist, können Sie sich möglicherweise nicht mehr anmelden.',
        unlink: 'Trennen',
        unlinkFailed: 'Das Konto konnte nicht getrennt werden.',
        unlinked: '{{provider}} wurde getrennt.',
        add: 'Weiteres Konto verknüpfen',
      },
      twoFactorSettings: {
        title: 'Zwei-Faktor-Authentifizierung',
        unavailable: 'Die Zwei-Faktor-Authentifizierung ist auf diesem BillManager-Server nicht aktiviert.',
        enabledSubtitle: 'Ihr Konto verlangt bei der Anmeldung eine zusätzliche Bestätigungsmethode.',
        disabledSubtitle: 'Fügen Sie eine zweite Bestätigungsmethode hinzu, um Ihr Konto zu schützen.',
        loading: 'Sicherheitsstatus wird geladen',
        loadFailed: 'Der Zwei-Faktor-Status konnte nicht geladen werden.',
        enabledNotice: 'Zwei-Faktor-Authentifizierung ist aktiviert.',
        disabledNotice: 'Zwei-Faktor-Authentifizierung ist deaktiviert.',
        methods: 'Bestätigungsmethoden',
        emailCodes: 'E-Mail-Einmalcodes',
        passkeys: 'Passkeys',
        registered_one: '{{count}} registriert',
        registered_other: '{{count}} registriert',
        recoveryCodes: 'Wiederherstellungscodes',
        available: 'Verfügbar',
        generate: 'Codes erstellen',
        turnOff: 'Zwei-Faktor-Authentifizierung deaktivieren',
        disableAll: 'Alle Methoden deaktivieren',
      },
      recovery: {
        panelTitle: 'Diese Wiederherstellungscodes speichern',
        panelDescription: 'Sie werden nur einmal angezeigt. Jeder Code kann einmal verwendet werden, wenn Ihre anderen Methoden nicht verfügbar sind.',
        accessibility: 'Wiederherstellungscodes: {{codes}}',
        shareTitle: 'BillManager-Wiederherstellungscodes',
        shareMessage: 'BillManager-Wiederherstellungscodes\n\n{{codes}}\n\nJeder Code kann einmal verwendet werden. Bewahren Sie sie sicher auf.',
        share: 'Sicher teilen oder speichern',
        title: 'Wiederherstellungscodes',
        subtitle: 'Verwenden Sie einen Code, wenn Sie nicht auf Ihre E-Mail oder Ihren Passkey zugreifen können.',
        regenerateTitle: 'Neue Wiederherstellungscodes erstellen?',
        regenerateWarning: 'Alle vorhandenen Wiederherstellungscodes funktionieren danach sofort nicht mehr.',
        generate: 'Erstellen',
        failed: 'Wiederherstellungscodes konnten nicht erstellt werden.',
        warning: 'Beim Erstellen eines neuen Satzes werden alle vorherigen Wiederherstellungscodes ungültig.',
        generateNew: 'Neue Codes erstellen',
      },
      emailSetup: {
        title: 'E-Mail-Einmalcodes',
        unavailable: 'E-Mail-Einmalcodes sind auf diesem BillManager-Server nicht aktiviert.',
        subtitle: 'Wir prüfen, ob Sicherheitscodes die E-Mail-Adresse Ihres Kontos erreichen.',
        sendFailed: 'Ein Einrichtungscode konnte nicht gesendet werden.',
        verifyFailed: 'Der Code konnte nicht bestätigt werden.',
        send: 'Einrichtungscode senden',
        verify: 'Bestätigen und aktivieren',
        resend: 'Neuen Code senden',
      },
      passkeys: {
        title: 'Passkeys',
        unavailable: 'Passkeys sind auf diesem BillManager-Server nicht aktiviert.',
        subtitle: 'Passkeys verwenden die Gerätesperre oder einen Sicherheitsschlüssel anstelle eines eingegebenen Codes.',
        defaultDevice: 'Mein Gerät',
        nameRequired: 'Geben Sie einen Namen für diesen Passkey ein',
        confirmationRequired: 'Geben Sie Ihr Passwort oder den Bestätigungscode ein',
        loading: 'Passkeys werden geladen',
        loadFailed: 'Passkeys konnten nicht geladen werden.',
        nativeUnavailable: 'Dieser Build enthält keinen nativen Passkey-Adapter.',
        optionsFailed: 'Registrierungsoptionen konnten nicht geladen werden.',
        registrationFailed: 'Der Passkey konnte nicht registriert werden.',
        registrationCancelled: 'Die Passkey-Registrierung wurde abgebrochen.',
        removed: 'Passkey entfernt.',
        removeFailed: 'Der Passkey konnte nicht entfernt werden.',
        addSection: 'Passkey hinzufügen',
        name: 'Passkey-Name',
        nameHint: 'Zum Beispiel: Persönliches iPhone',
        create: 'Passkey erstellen',
        registeredSection: 'Registrierte Passkeys',
        empty: 'Keine Passkeys registriert.',
        lastUsed: 'Zuletzt verwendet: {{date}}',
        neverUsed: 'Nie verwendet',
        removeTitle: '{{name}} entfernen?',
        removeDescription: 'Bestätigen Sie diese sicherheitsrelevante Änderung.',
        remove: 'Passkey entfernen',
      },
      disableTwoFactor: {
        title: 'Zwei-Faktor-Authentifizierung deaktivieren',
        subtitle: 'Dadurch werden alle eingerichteten zweiten Faktoren aus Ihrem Konto entfernt.',
        warning: 'Nach dieser Änderung melden Sie sich nur mit Ihrem Passwort oder einem verknüpften Konto an.',
        confirmTitle: 'Zwei-Faktor-Authentifizierung deaktivieren?',
        confirmWarning: 'Alle Passkeys und Wiederherstellungscodes werden aus diesem Konto entfernt.',
        disable: 'Deaktivieren',
        failed: 'Die Zwei-Faktor-Authentifizierung konnte nicht deaktiviert werden.',
        success: 'Zwei-Faktor-Authentifizierung ist deaktiviert.',
        action: 'Zwei-Faktor-Authentifizierung deaktivieren',
      },
      deleteAccount: {
        title: 'Konto löschen',
        unavailable: 'Nur der Kontoinhaber kann dieses BillManager-Konto dauerhaft löschen.',
        subtitle: 'Diese Aktion entfernt das gesamte Konto und alle zugehörigen Daten dauerhaft.',
        irreversibleTitle: 'Dies kann nicht rückgängig gemacht werden',
        irreversible: 'Exportieren Sie zuvor alle benötigten Daten. Andere Nutzer dieses Kontos verlieren ebenfalls den Zugriff.',
        typeDelete: 'Zum Bestätigen DELETE eingeben',
        typeDeleteError: 'Geben Sie DELETE exakt ein',
        passwordRequired: 'Geben Sie Ihr Passwort ein',
        confirmTitle: 'Dieses Konto dauerhaft löschen?',
        confirmWarning: 'Alle zugehörigen Nutzer, Rechnungsgruppen, Rechnungen, Zahlungen, Freigaben und Abonnementdaten werden entfernt. Dies kann nicht rückgängig gemacht werden.',
        deletePermanently: 'Dauerhaft löschen',
        failed: 'Das Konto konnte nicht gelöscht werden.',
        action: 'Konto dauerhaft löschen',
      },
      biometric: {
        title: 'BillManager ist gesperrt',
        subtitle: 'Entsperren Sie die App, um Rechnungen und Zahlungsinformationen anzuzeigen.',
        enrollmentChanged: 'Ihre biometrische Registrierung hat sich geändert. Bestätigen Sie einmal Ihr Kontopasswort, um die neue Registrierung zu schützen.',
        notEnrolled: 'Richten Sie in den Systemeinstellungen Biometrie oder einen Gerätecode ein und versuchen Sie es erneut.',
        verificationFailed: 'BillManager konnte Ihre Identität nicht bestätigen.',
        passwordRequired: 'Geben Sie Ihr BillManager-Passwort ein.',
        passwordFailed: 'BillManager konnte Ihr Passwort nicht bestätigen.',
        setupBiometrics: 'Richten Sie Biometrie in den Systemeinstellungen ein und versuchen Sie es erneut.',
        passwordLabel: 'BillManager-Passwort',
        verifyAccountPassword: 'Kontopasswort bestätigen',
        unlockApp: 'BillManager entsperren',
        verifying: 'Bestätigung läuft…',
        signOut: 'Zum Bestätigen der Identität abmelden',
        verifyPassword: 'Passwort bestätigen',
        unlock: 'Entsperren',
        reauthHelp: 'Nach der Bestätigung bindet BillManager die App-Sperre an die neu registrierte Biometrie.',
      },
    },
  },
} as const;
