/**
 * Mobile-only copy which has no direct equivalent in the shared web catalog.
 * Feature screens should continue to prefer the web keys where the semantics match.
 */
export const mobileParityResources = {
  en: {
    common: {
      cancel: 'Cancel',
      save: 'Save',
      done: 'Done',
      close: 'Close',
      delete: 'Delete',
      edit: 'Edit',
      retry: 'Try again',
      loading: 'Loading…',
      error: 'Error',
      success: 'Success',
      offline: 'Offline',
      connectionRequired: 'Connection required',
      pendingSync: 'Pending sync',
      pending: 'Pending',
      loadMore: 'Load more',
      all: 'All',
      income: 'Income',
      expenses: 'Expenses',
      optional: 'optional',
      unknown: 'Unknown',
      notAvailable: 'Not available',
      back: 'Back',
      add: 'Add',
      remove: 'Remove',
      create: 'Create',
      confirm: 'Confirm',
      networkError: 'Network error',
      user: 'User',
      admin: 'Admin',
    },
    telemetry: {
      title: 'Anonymous usage statistics',
      description: 'BillManager collects anonymous usage statistics to help improve the product. This data helps us understand which features are most valuable and guide development priorities.',
      collectedTitle: 'What we collect:',
      totalCounts: 'Total users, bills, and databases (counts only)',
      featureUsage: 'Feature usage (auto-pay, variable bills, mobile devices)',
      platformInfo: 'Platform information (Python version, operating system, database type)',
      instanceVersion: 'Anonymous instance ID and app version',
      neverTitle: 'What we never collect:',
      noPersonalInformation: 'Personal information (names, emails, addresses)',
      noFinancialData: 'Bill amounts or financial data',
      noBillContent: 'Bill names or descriptions',
      noPaymentHistory: 'Payment history or dates',
      documentation: 'See TELEMETRY.md for full details',
      footnote: 'You can change this preference at any time. All telemetry submissions are logged locally for transparency.',
      optOut: 'Opt out',
      accept: 'Accept & continue',
    },
    addBill: {
      newTitle: 'New Bill',
      expense: 'Expense',
      income: 'Income',
      nameIcon: 'Name & Icon',
      variable: 'Variable',
      useSpecificDates: 'Use specific month dates',
      specificDatesDetail: 'For schedules such as the 1st and 15th.',
      specificDatesA11y: 'Specific dates each month',
      accountOptional: 'Account (optional)',
      categoryOptional: 'Category (optional)',
      bucketRequired: 'Bucket *',
      autoPayment: 'Auto-payment enabled',
      localReminders: 'Local reminders',
      localRemindersDetail: 'Show due reminders on this device.',
      remindMe: 'Remind me',
      dueDay: 'Due day',
      dayBefore_one: '{{count}} day',
      dayBefore_other: '{{count}} days',
      notesOptional: 'Notes (optional)',
      errors: {
        amountRequired: 'Please enter an amount or mark as variable.',
        invalidSchedule: 'Invalid schedule',
        monthDates: 'Enter one or more month dates from 1 through 31.',
        weekday: 'Choose at least one weekday.',
        saveTitle: 'Could not save bill',
        saveBody: 'Try again.',
      },
    },
    bills: {
      archived: 'Archived',
      active: 'Active',
      searchA11y: 'Search bills',
      noBills: 'No bills found',
      syncPending: 'Changes are waiting to synchronize.',
      variable: 'Variable',
      shared: 'Shared',
      sharedBy: 'Shared by {{name}}',
      myPortion: 'My portion: {{amount}}',
      dueAgo_one: 'Due {{count}} day ago',
      dueAgo_other: 'Due {{count}} days ago',
      dueToday: 'Due today',
      dueIn_one: 'Due in {{count}} day',
      dueIn_other: 'Due in {{count}} days',
      allCount: 'All ({{count}})',
      archivedCount: 'Archived ({{count}})',
      summary: '{{expenses}} expenses · {{income}} deposits',
      showing: 'Showing {{filter}}{{query}} ({{count}} result)',
      showing_other: 'Showing {{filter}}{{query}} ({{count}} results)',
      matching: ' matching “{{query}}”',
      filterExpenses: 'expenses',
      filterIncome: 'income',
      filterArchived: 'archived bills',
      filterAll: 'all',
      noArchived: 'No archived bills',
      noMatches: 'No matching bills',
      noBillsYet: 'No bills yet',
      adjustSearch: 'Try adjusting your search or filters.',
      addFirst: 'Add your first bill to get started.',
      selectGroup: 'Select bill group',
      filtersA11y: 'Bill filters{{active}}',
      activeFilters: ', {{count}} active',
      filters: 'Filters',
      sortA11y: 'Sort bills, {{sort}}',
      loadMoreA11y: 'Load more bills, {{shown}} of {{total}} shown',
      loadMore: 'Load more · {{shown}} of {{total}}',
      reset: 'Reset',
      filterTitle: 'Filter bills',
      dueDate: 'Due date',
      from: 'From',
      to: 'To',
      dueFromA11y: 'Bills due from date',
      dueToA11y: 'Bills due through date',
      checkDue: 'Check due dates',
      invalidDue: 'Enter dates in YYYY-MM-DD format.',
      dueOrder: 'The start date must be on or before the end date.',
      allAccounts: 'All accounts',
      allCategories: 'All categories',
      sortTitle: 'Sort bills',
      sortDueSoonest: 'Due soonest',
      sortDueLatest: 'Due latest',
      sortNameAsc: 'Name A–Z',
      sortNameDesc: 'Name Z–A',
      sortHighest: 'Highest amount',
      sortLowest: 'Lowest amount',
    },
    billDetail: {
      invalidAmount: 'Please enter a valid payment amount.',
      recorded: 'Payment recorded successfully.',
      recordFailed: 'Failed to record payment.',
      markedUnpaid: 'Portion marked as unpaid.',
      markedPaid: 'Portion marked as paid.',
      updateFailed: 'Failed to update payment status.',
      archiveFailed: 'Failed to archive bill.',
      restoreFailed: 'Failed to restore bill.',
      deleteOffline: 'Permanent deletion requires an active connection. You can archive this bill while offline.',
      deleteFailed: 'Failed to delete bill.',
      paymentNotesPlaceholder: 'Add payment notes…',
      notesPlaceholder: 'Add notes…',
      advanceDueA11y: 'Advance next due date',
      notFound: 'Bill not found',
      goBack: 'Go back',
      back: 'Back',
      nextDue: 'Next due',
      autoPay: 'Auto-pay',
      yes: 'Yes',
      no: 'No',
      sharingDetails: 'Sharing details',
      myPortion: 'My portion',
      paymentStatus: 'Payment status',
      paid: 'Paid',
      notPaid: 'Not paid',
      recordPayment: 'Record payment',
      restore: 'Restore',
      archive: 'Archive',
      shareBill: 'Share bill',
      deleteBill: 'Delete bill',
      paymentHistory: 'Payment history',
      swipeHint: 'Swipe to edit or delete',
      paymentDate: 'Payment date',
      advanceDue: 'Advance next due date',
      advanceDueBody: 'Move this recurring bill to its next scheduled occurrence.',
      record: 'Record',
      editPayment: 'Edit payment',
      deletePayment: 'Delete payment?',
      deletePaymentBody: 'This payment will be permanently removed.',
      updatePaymentFailed: 'Failed to update payment.',
      deletePaymentFailed: 'Failed to delete payment.',
    },
    payments: {
      title: 'Payment history',
      loadingTitle: 'Loading payments',
      loadingBody: 'Getting payment history and totals.',
      unavailableTitle: 'Payments unavailable',
      unavailableBody: 'Payment history could not be loaded.',
      restrictedTitle: 'Payment history is restricted',
      restrictedBody: 'Your role does not have access to payment history.',
      count_one: '{{count}} payment across {{bucket}}.',
      count_other: '{{count}} payments across {{bucket}}.',
      sortA11y: 'Sort payments, {{sort}}',
      offlineSaved: 'Offline · showing saved payments{{updated}}',
      netTotal: 'Net total',
      totalsA11y: 'Payment totals. Income {{income}}, expenses {{expenses}}, net {{net}}',
      searchA11y: 'Search payment history',
      searchPlaceholder: 'Search bill, account, category, or note',
      type: 'Payment type',
      filterA11y: '{{label}} filter',
      exportA11y: 'Export payment history',
      exportFormatA11y: '{{format}} payment history',
      payments: 'Payments',
      emptyTitle: 'No matching payments',
      emptyBody: 'Change the filters or record a payment from a bill.',
      pageA11y: 'Load page {{page}} of {{total}}',
      rowA11y: '{{name}}, {{direction}} {{amount}}, {{details}}{{pending}}',
      editA11y: 'Edit {{name}} payment',
      deleteA11y: 'Delete {{name}} payment',
      deleteHint: 'A confirmation appears before deleting.',
      plus: 'plus',
      minus: 'minus',
      exportUnavailable: 'Export unavailable',
      exportFailed: 'Could not create this export.',
      checkDetails: 'Check payment details',
      invalidDetails: 'Enter a valid amount and a date in YYYY-MM-DD format.',
      deleteTitle: 'Delete payment?',
      deleteBody: 'This payment and its totals will be removed.',
      amountA11y: 'Payment amount',
      dateA11y: 'Payment date',
      notesA11y: 'Payment notes',
      resetFilters: 'Reset filters to All',
      any: 'Any',
      anyAmount: 'Any amount',
      anyDate: 'Any date',
      allAccounts: 'All accounts',
      allCategories: 'All categories',
      allBuckets: 'All buckets',
      print: 'Print',
      share: 'Share',
      filterDates: 'Payment dates',
      filterAmounts: 'Payment amounts',
      account: 'Account',
      category: 'Category',
      bucket: 'Bucket',
      dateHelp: 'Choose a quick period or enter an inclusive custom range.',
      thisMonth: 'This month',
      lastThreeMonths: 'Last 3 months',
      lastTwelveMonths: 'Last 12 months',
      customRange: 'Custom range',
      from: 'From',
      through: 'Through',
      fromDateA11y: 'Payments from date',
      throughDateA11y: 'Payments through date',
      applyDates: 'Apply custom dates',
      amountHelp: 'Filter by absolute payment amount. Leave either field empty for an open range.',
      minimumAmount: 'Minimum amount',
      maximumAmount: 'Maximum amount',
      minimumA11y: 'Minimum payment amount',
      maximumA11y: 'Maximum payment amount',
      noMinimum: 'No minimum',
      noMaximum: 'No maximum',
      applyAmount: 'Apply amount range',
      checkDateRange: 'Check date range',
      dateRequired: 'Enter at least one date in YYYY-MM-DD format.',
      dateOrder: 'The start date must be on or before the end date.',
      checkAmountRange: 'Check amount range',
      amountRangeError: 'Enter positive amounts with the minimum no greater than the maximum.',
      fromDate: 'From {{date}}',
      throughDate: 'Through {{date}}',
      sortTitle: 'Sort payments',
      sortNewest: 'Newest first',
      sortOldest: 'Oldest first',
      sortHighest: 'Highest amount',
      sortLowest: 'Lowest amount',
      sortNameAsc: 'Bill name A–Z',
      sortNameDesc: 'Bill name Z–A',
      editPayment: 'Edit payment',
      saving: 'Saving…',
      receivedShared: 'Received shared payment · managed by the payer',
      sharedManaged: 'Shared payment · managed from the shared bill',
      billFallback: 'Bill {{id}}',
      currentBucket: 'Current bucket',
      exportTitle: 'BillManager payment history',
      csvDate: 'Date',
      csvBill: 'Bill',
      csvBucket: 'Bucket',
      csvAccount: 'Account',
      csvCategory: 'Category',
      csvDirection: 'Direction',
      csvAmount: 'Amount',
      csvNotes: 'Notes',
    },
    analytics: {
      loadingTitle: 'Loading analytics',
      loadingBody: 'Calculating trends and forecasts.',
      unavailableTitle: 'Analytics unavailable',
      unavailableBody: 'Analytics could not be loaded.',
      restrictedTitle: 'Analytics are restricted',
      restrictedBody: 'Your role does not have access to analytics.',
      subtitle: 'Annual trends, comparisons, and forecasts for {{bucket}}.',
      yearA11y: 'Analytics year, {{year}}',
      chooseYear: 'Choose a year',
      closeYearPicker: 'Close year picker',
      offlineSaved: 'Offline · showing the latest saved analytics snapshot{{updated}}',
      annualSummary: 'Annual summary',
      netCashFlow: 'Net cash flow',
      yearComparison: '{{current}} compared with {{previous}}',
      categories: 'Categories',
      accounts: 'Accounts',
      noCategoryData: 'No category data for this period.',
      noAccountData: 'No account data for this period.',
      monthlyComparison: 'Monthly comparison',
      yearlyView: 'Yearly view',
      cashFlowForecast: 'Cash-flow forecast',
      forecast: 'forecast',
      in: '{{amount}} in',
      out: '{{amount}} out',
      detailTitle: 'Analytics detail',
      detailBody: '{{section}} is summarized on this page and available to screen readers.',
      notEnoughTitle: 'Not enough activity yet',
      notEnoughBody: 'Record payments to build monthly trends, comparisons, and cash-flow forecasts.',
      range: 'Analytics range',
      sixMonths: '6 months',
      twelveMonths: '12 months',
      year: 'Year',
      details: 'Details',
      openDetailsA11y: 'Open {{label}} details',
      savingsRate: '{{value}}% savings rate',
      yearOverYear: 'Year over year',
      netChange: 'Net change',
      categoryTrends: 'Category trends',
      byAccount: 'By account',
      noCategorized: 'No categorized expenses.',
      noAccounts: 'No account data.',
      yearlyHistory: 'Yearly history',
      shareOfTotal: '{{value}}% of total',
      priorPeriod: '{{value}}% vs prior period',
      up: 'up',
      down: 'down',
      breakdownA11y: '{{label}}, {{amount}}, {{share}} percent{{change}}',
      changeA11y: ', {{direction}} {{value}} percent',
      annualA11y: '{{year}} annual summary. Income {{income}}, expenses {{expenses}}, net {{net}}, savings rate {{rate}} percent.',
      monthlyA11y: 'Monthly comparison. {{summary}}',
      monthlyPointA11y: '{{label}}: income {{income}}, expenses {{expenses}}, net {{net}}',
      yearlyA11y: 'Yearly history. {{summary}}',
      yearlyPointA11y: '{{year}} net {{net}}',
      cashFlowA11y: 'Cash flow from {{first}} to {{last}}. Ending balance changes from {{start}} to {{end}}. {{count}} forecast period.',
      cashFlowA11y_other: 'Cash flow from {{first}} to {{last}}. Ending balance changes from {{start}} to {{end}}. {{count}} forecast periods.',
      noCashFlowA11y: 'No cash-flow data is available.',
      currentBucket: 'Current bucket',
      yoyA11y: '{{current}} compared with {{previous}}. Income {{incomeDirection}} {{incomeValue}} percent. Expenses {{expenseDirection}} {{expenseValue}} percent. Net change {{net}}.',
    },
    collaboration: {
      loadingTitle: 'Loading shared bills',
      loadingBody: 'Getting shares and invitations.',
      unavailableTitle: 'Sharing unavailable',
      unavailableBody: 'Shared bills could not be loaded.',
      restrictedTitle: 'Sharing is restricted',
      restrictedBody: 'Your role cannot view or manage shared bills.',
      subtitle: 'Invitations and splits in {{bucket}}.',
      shareA11y: 'Share a bill',
      shareBill: 'Share bill',
      offlineSaved: 'Offline · saved sharing data{{updated}}. Reconnect to change access or invitations.',
      emptyTitle: 'No shared bills',
      emptyBody: 'Share a bill to divide expenses and track who has paid.',
      pendingInvites: 'Pending invitations ({{count}})',
      sharedBills: 'Shared bills ({{count}})',
      noActive: 'No active shared bills.',
      invitationFrom: 'Invitation from {{name}}',
      invitationSent: 'Invitation sent to {{email}}',
      from: 'From {{name}}',
      sentTo: 'Sent to {{email}}',
      acceptA11y: 'Accept invitation to {{name}}',
      declineA11y: 'Decline invitation to {{name}}',
      revokeInviteA11y: 'Revoke invitation sent to {{email}}',
      ownedBy: 'owned by {{name}}',
      yourShare: 'Your share',
      people_one: '{{count}} person',
      people_other: '{{count}} people',
      openA11y: '{{name}}, {{owner}}, your share {{share}} of {{total}}, {{split}}, {{due}}{{pending}}. Open shared bill',
      editSplit: 'Edit split',
      editSplitA11y: 'Edit split for {{name}}',
      revoke: 'Revoke',
      stopSharingA11y: 'Stop sharing {{name}}',
      revokeHint: 'A confirmation appears before revoking access.',
      revokeTitle: 'Revoke bill share?',
      revokeBody: 'The recipient will lose access to this bill.',
      equalSplit_one: 'Split equally with {{count}} person',
      equalSplit_other: 'Split equally with {{count}} people',
      percentageSplit: '{{value}} percent share',
      fixedSplit: '{{amount}} fixed share',
      sent: 'Sent {{date}}',
      you: 'You',
      supportRequired: 'This BillManager server does not advertise sharing support.',
      noSavedData: 'No saved sharing data is available yet. Reconnect and refresh once to make it available offline.',
      sharesUnavailable: 'Shares for {{name}} are unavailable.',
      acceptFailed: 'Failed to accept the shared bill.',
      declineTitle: 'Decline invitation?',
      declineBody: 'Decline this bill-sharing invitation?',
      declineFailed: 'Failed to decline the shared bill.',
      leaveFailed: 'Failed to leave the shared bill.',
      lastPaid: 'Last paid: {{date}} ({{amount}})',
      lastPayment: 'Last payment',
      counts: '{{active}} active · {{pending}} pending',
      emptyReceivedBody: 'Bills shared with you will appear here.',
      activeSharedBills: 'Active shared bills',
      leaveTitle: 'Leave shared bill?',
      leaveBody: 'Stop watching this shared bill?',
      leave: 'Leave shared bill',
    },
    settlements: {
      loadingTitle: 'Loading settlements',
      loadingBody: 'Calculating shared balances.',
      unavailableTitle: 'Settlements unavailable',
      unavailableBody: 'Shared balances could not be loaded.',
      restrictedTitle: 'Settlements are restricted',
      restrictedBody: 'Your role cannot view settlements.',
      offlineSaved: 'Offline · showing saved settlement data{{updated}}. Reconnect to settle a balance.',
      connectionRequired: 'Settlements require a connection.',
      noOpenBills: 'No open shared bills.',
      settleTitle: 'Settle this balance?',
      settleBody_one: '{{count}} shared bill totaling {{amount}} will be marked paid.',
      settleBody_other: '{{count}} shared bills totaling {{amount}} will be marked paid.',
      historyTitle: 'Settlement history',
      historyBody_one: '{{count}} recently settled share.',
      historyBody_other: '{{count}} recently settled shares.',
      subtitle: 'Balances from shared bills in {{bucket}}.',
      supportRequired: 'This BillManager server does not advertise settlement support.',
      noSavedData: 'No saved settlement data is available yet. Reconnect and refresh once to make it available offline.',
      summaryA11y: 'Settlement summary. Owed to you {{owed}}, you owe {{owe}}, net {{net}}',
      outstanding_one: '{{count}} outstanding person',
      outstanding_other: '{{count}} outstanding people',
      people: 'People',
      settled: 'Settled',
      owesYou: 'owes you',
      youOwe: 'you owe',
      sharedBills_one: '{{count}} shared bill',
      sharedBills_other: '{{count}} shared bills',
      personA11y: '{{name}}, {{direction}} {{amount}}, {{bills}}, {{activity}}{{pending}}. Open settlement details',
      markBalanceA11y: 'Mark balance with {{name}} paid',
      connectHint: 'Connect to the server to settle this balance.',
      markHint: 'Records the full outstanding balance as settled.',
      everyoneSettled: 'Everyone is settled up',
      everyoneSettledBody: 'New balances appear after shared payments are recorded.',
      recent: 'Recent settlements',
      viewAll: 'View all',
      noHistory: 'No settlement history yet.',
      paid: '{{payer}} paid {{payee}}',
      paidA11y: '{{payer}} paid {{payee}} {{amount}}, {{date}}',
      openSharedBills: 'Open shared bills',
    },
    administration: {
      loadingTitle: 'Loading administration',
      loadingBody: 'Getting users, invitations, and bill groups.',
      unavailableTitle: 'Administration unavailable',
      unavailableBody: 'Administration data could not be loaded.',
      restrictedTitle: 'Administrator access required',
      restrictedBody: 'Your account cannot manage this server.',
      connectionTitle: 'Connection required',
      connectionBody: 'Administration requires a fresh server connection.',
      subtitle: '{{users}} users · {{groups}} bill groups',
      users: 'Users',
      invitations: 'Invitations',
      groups: 'Bill groups',
      role: 'Role: {{role}}',
      expires: 'Expires {{date}}',
      statusActive: 'Active',
      statusSuspended: 'Suspended',
      statusInvited: 'Invited',
      statusPasswordChange: 'Password change required',
      deleteUserTitle: 'Delete user?',
      deleteUserBody: 'This user will lose access to every assigned bill group.',
      revokeInviteTitle: 'Revoke invitation?',
      revokeInviteBody: 'The invitation link will stop working.',
      permissionRequired: 'Only account owners and administrators can manage users, invitations, and bill groups.',
      connectionFreshBody: 'Administration always loads fresh permissions and directory data from the server. Reconnect to continue.',
      unavailableData: 'Administration data is unavailable.',
      title: 'Administration',
      manageAs: 'Manage people and data access as {{role}}.',
      section: 'Administration section',
      usersCount: 'Users ({{count}})',
      invitesCount: 'Invites ({{count}})',
      groupsCount: 'Groups ({{count}})',
      pendingInvites: 'Pending invitations',
      groupsAccess: 'Groups and access',
      addUser: 'Add user',
      inviteUser: 'Invite user',
      addGroup: 'Add group',
      noItems: 'No {{section}}',
      startWith: 'Use {{action}} to get started.',
      nothing: 'There is nothing to manage in this section.',
      audit: 'Administrative changes are confirmed and audited by the server before additional mutations.',
      noGroups: 'No groups',
      lastLogin: 'last login {{date}}',
      editA11y: 'Edit {{name}}',
      accessA11y: 'Change access for {{name}}',
      deleteA11y: 'Delete {{name}}',
      resendA11y: 'Resend invite to {{email}}',
      revokeA11y: 'Revoke invite to {{email}}',
      manageAccessA11y: 'Manage access for {{name}}',
      member_one: '{{count}} member',
      member_other: '{{count}} members',
      owner_one: '{{count}} owner',
      owner_other: '{{count}} owners',
      invitedA11y: '{{email}}, invited as {{role}} by {{name}}, {{groups}}, {{sent}}, {{expires}}',
      groupA11y: '{{name}}, {{members}}, {{owners}}{{database}}',
      databaseA11y: ', database {{name}}',
      userA11y: '{{name}}, {{email}}, {{role}}, {{status}}, {{groups}}{{lastLogin}}',
      noEmail: 'No email',
      groupFallback: 'Group {{id}}',
      administrator: 'Administrator',
    },
    userManagement: {
      loadFailed: 'Failed to load users',
      cannotChangeOwnRole: 'You cannot change your own role.',
      changeRoleTitle: 'Change role',
      changeRoleBody: 'Change {{name}} from {{current}} to {{next}}?',
      updateRoleFailed: 'Failed to update role.',
      cannotDeleteOwn: 'You cannot delete your own account here.',
      deleteTitle: 'Delete user?',
      deleteBody: 'Delete {{name}}? This action cannot be undone.',
      deleted: 'User deleted.',
      deleteFailed: 'Failed to delete user.',
      updated: 'User updated.',
      updateFailed: 'Failed to update user.',
      usernameRequired: 'Username is required.',
      passwordRequired: 'Password is required.',
      passwordLength: 'Password must be at least 8 characters.',
      chooseGroup: 'Select at least one bill group.',
      created: 'User created successfully.',
      createFailed: 'Failed to create user.',
      you: 'you',
      joined: 'Joined {{date}}',
      demote: 'Demote',
      promote: 'Promote',
      title: 'User management',
      noUsers: 'No users found',
      count_one: '{{count}} user',
      count_other: '{{count}} users',
      editUser: 'Edit user',
      createUser: 'Create user',
      email: 'Email',
      role: 'Role',
      usernameLabel: 'Username *',
      usernamePlaceholder: 'Enter username',
      emailOptional: 'Email (optional)',
      passwordLabel: 'Password *',
      passwordPlaceholder: 'At least 8 characters',
      billGroupAccess: 'Bill group access *',
    },
    invitations: {
      loadFailed: 'Failed to load invitations',
      emailRequired: 'Enter an email address.',
      chooseGroup: 'Select at least one bill group.',
      sent: 'Invitation sent.',
      sendFailed: 'Failed to send invitation.',
      resendTitle: 'Resend invitation?',
      resendBody: 'Resend the invitation to {{email}}?',
      resend: 'Resend',
      resent: 'Invitation resent.',
      resendFailed: 'Failed to resend invitation.',
      cancelTitle: 'Cancel invitation?',
      cancelBody: 'Cancel the invitation for {{email}}?',
      cancelAction: 'Yes, cancel',
      cancelFailed: 'Failed to cancel invitation.',
      expired: 'Expired',
      pending: 'Pending',
      metadata: 'Role: {{role}} · Sent {{date}}',
      expiredOn: 'Expired {{date}}',
      expiresOn: 'Expires {{date}}',
      title: 'Invitations',
      invite: 'Invite',
      emailWarning: 'Email is not configured. Invitation emails will not be sent automatically. Share the invitation link manually.',
      noPending: 'No pending invitations',
      emptyBody: 'Tap “Invite” to invite a new user.',
      count_one: '{{count}} pending invitation',
      count_other: '{{count}} pending invitations',
      inviteUser: 'Invite user',
      emailAddress: 'Email address',
      billGroups: 'Bill groups',
      sendInvite: 'Send invite',
    },
    groupManagement: {
      loadFailed: 'Failed to load bill groups',
      displayNameRequired: 'Enter a display name.',
      internalNameRequired: 'Enter an internal name.',
      updated: 'Bill group updated.',
      created: 'Bill group created.',
      saveFailed: 'Failed to save bill group.',
      deleteTitle: 'Delete bill group?',
      deleteBody: 'Delete “{{name}}”? This permanently deletes all bills and payments in this group.',
      deleted: 'Bill group deleted.',
      deleteFailed: 'Failed to delete bill group.',
      addAccessFailed: 'Failed to add user access.',
      removeAccessTitle: 'Remove access?',
      removeAccessBody: 'Remove {{user}}’s access to “{{group}}”?',
      removeAccessFailed: 'Failed to remove user access.',
      accessCount_one: '{{count}} user with access:',
      accessCount_other: '{{count}} users with access:',
      manageUsers: 'Manage users',
      deleteGroup: 'Delete group',
      title: 'Bill groups',
      new: 'New',
      noGroups: 'No bill groups yet',
      emptyBody: 'Tap “New” to create your first group.',
      count_one: '{{count}} bill group',
      count_other: '{{count}} bill groups',
      editTitle: 'Edit bill group',
      newTitle: 'New bill group',
      internalName: 'Internal name',
      internalPlaceholder: 'personal, business, etc.',
      immutable: 'Cannot be changed after creation',
      displayName: 'Display name',
      displayPlaceholder: 'Personal bills, business expenses, etc.',
      description: 'Description (optional)',
      descriptionPlaceholder: 'What this bill group is for',
      manageAccess: 'Manage access',
      usersWithAccess: 'Users with access',
      addUsers: 'Add users',
      noUsers: 'No users available',
    },
    billing: {
      loadingTitle: 'Loading billing',
      unavailableTitle: 'Billing unavailable',
      unavailableBody: 'Billing information could not be loaded.',
      restrictedTitle: 'Billing access required',
      restrictedBody: 'Only an account owner or administrator can manage billing.',
      connectionBody: 'Billing actions require a fresh server connection.',
      openPortalA11y: 'Open billing portal',
      checkoutFailed: 'Could not start checkout.',
      portalFailed: 'Could not open the billing portal.',
      selfHostedA11y: 'Self-hosted unlimited plan. No BillManager subscription or hosted usage limits.',
      loadingPlan: 'Loading plan and usage',
      loadingBody: 'Getting subscription details.',
      planUnavailable: 'Plan and usage data could not be loaded.',
      ownerOnly: 'Only an owner can view or manage billing.',
      connectFresh: 'Connect to BillManager to load current subscription, trial, and usage data.',
      titleSelfHosted: 'Self-hosted plan',
      titleCloud: 'Plan and billing',
      subtitleSelfHosted: 'Usage is managed by your own BillManager server.',
      subtitleCloud: 'Subscription, trial, and deployment usage.',
      unlimitedSelfHosted: 'Unlimited, self-hosted',
      selfHostedBody: 'No BillManager subscription is required. Capacity and availability depend on this server.',
      trialA11y_one: 'Trial, {{count}} day remaining, ends {{date}}',
      trialA11y_other: 'Trial, {{count}} days remaining, ends {{date}}',
      trialRemaining_one: '{{count}} day left in your trial',
      trialRemaining_other: '{{count}} days left in your trial',
      ends: 'Ends {{date}}',
      renews: 'Renews {{date}}',
      accessEnds: 'Access ends {{date}}',
      noRenewal: 'No renewal scheduled',
      manage: 'Manage',
      usage: 'Usage',
      noUsage: 'No usage data',
      noUsageBody: 'Usage will appear after the server reports its first billing period.',
      availablePlans: 'Available plans',
      plansUnavailable: 'Plans are not available',
      plansUnavailableBody: 'Keep the current plan and try again after the server refreshes its catalog.',
      current: 'Current',
      recommended: 'Recommended',
      currentPlanA11y: ', current plan',
      recommendedA11y: ', recommended',
      choose: 'Choose {{name}}',
      unlimitedUsage: '{{used}} {{unit}}, unlimited',
      limitedUsage: '{{used}} of {{limit}} {{unit}}, {{percent}} percent used',
      usageA11y: '{{label}}, {{usage}}',
      currentUsage: '{{used}} · Unlimited',
      currentUsageLimited: '{{used}} / {{limit}} {{unit}}',
      perMonth: 'per month',
      perYear: 'per year',
      basicDescription: 'Core planning, analytics, and sharing',
      plusDescription: 'More family members, bill groups, and priority access',
      billsUnit: 'bills',
      groupsUnit: 'groups',
      selfHostedUnlimited: 'Self-hosted unlimited',
      cancels: 'Cancels {{date}}',
    },
    deviceSecurity: {
      title: 'App lock & widget privacy',
      intro: 'Protect local financial data on this device.',
      biometricLock: 'Biometric app lock',
      biometricDetail: 'Require Face ID, Touch ID, or Android biometrics when opening BillManager.',
      unavailableTitle: 'Biometrics unavailable',
      unavailableBody: 'Set up Face ID, Touch ID, Android biometrics, or a device passcode in system settings.',
      widgetAmounts: 'Show amounts in widgets',
      widgetAmountsA11y: 'Show amounts in home screen widgets',
      widgetAmountsDetail: 'Amounts are hidden by default. Enabling this can expose financial information on your home screen.',
      privacyDefault: 'Privacy-first default',
      privacyDefaultBody: 'Notification and widget amounts remain hidden unless you explicitly enable them.',
      screenTitle: 'Device security',
      screenIntro: 'These controls protect local data and reminders on this device. Account passkeys, 2FA, and recovery codes remain server-managed.',
      biometricBackground: 'Lock BillManager after it stays in the background.',
      reminderPermission: 'Local reminder permission',
      reminderAllowed: 'Allowed on this device',
      reminderDenied: 'Denied · reminders remain in the inbox',
      reminderReview: 'Review system notification permission',
      widgetDetail: 'Amounts are hidden by default and may be visible while the device is locked.',
      encryptedStorage: 'Bills, payments, conflicts, and outbox changes are stored in SQLCipher-encrypted SQLite. Encryption material and credentials remain in the platform secure store.',
      passkeysSupported: 'This server supports passkeys. Open Account security to manage credentials and recovery codes.',
      passkeysUnsupported: 'This server does not advertise passkey support.',
    },
    conflicts: {
      title: 'Sync conflicts',
      subtitle: 'Choose which version to keep. Destructive conflicts are never resolved automatically.',
      syncA11y: 'Synchronize now',
      emptyTitle: 'No sync conflicts',
      emptyBody: 'Your offline changes are in sync.',
      useServer: 'Use server version',
      keepMine: 'Keep my changes',
      useServerTitle: 'Use server version?',
      useServerBody: 'Your pending changes to this item will be discarded.',
      serverChanged: 'Server changed {{date}}',
      reasonModified: 'This item changed on the server.',
      reasonDeleted: 'This item was deleted on the server.',
      reasonPermission: 'Your permission to change this item changed.',
      screenTitle: 'Offline & conflicts',
      synchronizing: 'Synchronizing changes…',
      connected: 'Connected',
      offlineDetail: 'Offline · changes stay encrypted on this device',
      syncing: 'Syncing…',
      syncNow: 'Sync now',
      lastSync: 'Last synchronized {{date}}',
      neverSynced: 'This workspace has not completed its first synchronization.',
      noDecisions: 'No decisions needed',
      retryQueued: 'BillManager will retry queued changes in order when the connection returns.',
      changedAfterEdit: 'The server changed this {{entity}} after your offline edit.',
      serverUpdated: 'Server version updated {{date}}',
      useServerA11y: 'Use server version for {{name}}',
      keepMineA11y: 'Keep my changes for {{name}}',
    },
    profiles: {
      title: 'Server profiles',
      subtitle: 'Each server keeps credentials, bill groups, cached data, and queued changes isolated.',
      active: 'Active',
      verified: 'Verified {{date}}',
      neverVerified: 'Not verified yet',
      switchTitle: 'Switch server?',
      switchBody: 'BillManager will close the current session and load this server’s isolated workspace.',
      switch: 'Switch',
      add: 'Add self-hosted server',
      addTitle: 'Add server',
      displayName: 'Display name',
      displayNameA11y: 'Server display name',
      displayNamePlaceholder: 'Home server',
      url: 'Server URL',
      urlA11y: 'BillManager server URL',
      verify: 'Verify & save',
      verifying: 'Verifying…',
      httpsNotice: 'Production profiles require HTTPS with a system-trusted certificate.',
      serversTitle: 'Servers',
      deploymentA11y: '{{name}}, {{mode}}',
      verifiedServer: 'Verified · server {{version}}',
      verificationRequired: 'Verification required',
      verifyActive: 'Verify active server',
      checking: 'Checking…',
      addShort: 'Add',
      verifyFailed: 'Could not verify this server.',
      developmentNotice: 'Development builds may use HTTP for local testing.',
      validationNotice: 'BillManager validates certificate trust, health, capabilities, and mobile contract compatibility before saving the profile.',
      preparingA11y: 'Preparing BillManager',
      preparingWorkspace: 'Preparing your secure workspace…',
    },
    upgrade: {
      title: 'Server upgrade required',
      body: 'This BillManager server does not support the mobile contract required by this app.',
      serverVersion: 'Server version',
      mobileContract: 'Mobile contract',
      requiredContract: 'Required contract',
      minimumAppVersion: 'Minimum mobile version',
      verify: 'Check again',
      verifyA11y: 'Verify server compatibility again',
      anotherServer: 'Use another server',
      anotherServerA11y: 'Use another BillManager server',
      help: 'Update the server or choose a compatible profile. Your local data remains isolated and encrypted.',
      updateTitle: 'Update BillManager',
      versionBody: '{{profile}} requires mobile version {{minimum}}. This device is running {{current}}.',
      versionDetail: 'Your local data has not been changed. Install the newest app version, then verify the server again.',
      checking: 'Checking…',
      serverConnections: 'Server connections',
      server: 'Server {{version}}',
    },
    widget: {
      nextUp: 'Next up',
      noUpcoming: 'No upcoming bills',
      caughtUp: 'You’re all caught up',
      remainingThisMonth: '{{amount}} remaining this month',
    },
    share: {
      invalidPercentage: 'Please enter a valid percentage from 1 to 100.',
      invalidFixed: 'Please enter a valid fixed amount.',
      success: 'Bill shared successfully.',
      revokeTitle: 'Revoke share',
      revokeBody: 'Are you sure you want to stop sharing this bill with this user?',
      splitOptional: 'Split configuration (optional)',
      none: 'None',
      percentagePlaceholder: 'Enter percentage (for example, 50)',
      amountPlaceholder: 'Enter amount',
      fullAmount: 'Full amount',
      equal: '50/50',
      usernameOrEmail: 'Username or email',
      usernameOrEmailPlaceholder: 'Enter username or email',
      usernamePlaceholder: 'Enter username',
    },
  },
  de: {
    common: {
      cancel: 'Abbrechen', save: 'Speichern', done: 'Fertig', close: 'Schließen', delete: 'Löschen', edit: 'Bearbeiten', retry: 'Erneut versuchen', loading: 'Wird geladen…', error: 'Fehler', success: 'Erfolgreich', offline: 'Offline', connectionRequired: 'Verbindung erforderlich', pendingSync: 'Synchronisierung ausstehend', pending: 'Ausstehend', loadMore: 'Mehr laden', all: 'Alle', income: 'Einnahmen', expenses: 'Ausgaben', optional: 'optional', unknown: 'Unbekannt', notAvailable: 'Nicht verfügbar', back: 'Zurück', add: 'Hinzufügen', remove: 'Entfernen', create: 'Erstellen', confirm: 'Bestätigen', networkError: 'Netzwerkfehler', user: 'Nutzer', admin: 'Admin',
    },
    telemetry: {
      title: 'Anonyme Nutzungsstatistiken',
      description: 'BillManager erfasst anonyme Nutzungsstatistiken, um das Produkt zu verbessern. Diese Daten helfen uns zu verstehen, welche Funktionen besonders wertvoll sind, und unsere Entwicklungsprioritäten festzulegen.',
      collectedTitle: 'Was wir erfassen:',
      totalCounts: 'Gesamtzahl der Nutzer, Rechnungen und Datenbanken (nur Anzahlen)',
      featureUsage: 'Nutzung von Funktionen (automatische Zahlung, variable Rechnungen, mobile Geräte)',
      platformInfo: 'Plattforminformationen (Python-Version, Betriebssystem, Datenbanktyp)',
      instanceVersion: 'Anonyme Instanz-ID und App-Version',
      neverTitle: 'Was wir niemals erfassen:',
      noPersonalInformation: 'Personenbezogene Daten (Namen, E-Mail-Adressen, Anschriften)',
      noFinancialData: 'Rechnungsbeträge oder Finanzdaten',
      noBillContent: 'Rechnungsnamen oder -beschreibungen',
      noPaymentHistory: 'Zahlungsverlauf oder Datumsangaben',
      documentation: 'Alle Einzelheiten finden Sie in TELEMETRY.md',
      footnote: 'Sie können diese Einstellung jederzeit ändern. Alle Telemetrieübertragungen werden zur Nachvollziehbarkeit lokal protokolliert.',
      optOut: 'Ablehnen',
      accept: 'Zustimmen und fortfahren',
    },
    addBill: {
      newTitle: 'Neue Rechnung', expense: 'Ausgabe', income: 'Einnahme', nameIcon: 'Name & Symbol', variable: 'Variabel', useSpecificDates: 'Bestimmte Monatstage verwenden', specificDatesDetail: 'Für Zeitpläne wie den 1. und 15.', specificDatesA11y: 'Bestimmte Termine pro Monat', accountOptional: 'Konto (optional)', categoryOptional: 'Kategorie (optional)', bucketRequired: 'Gruppe *', autoPayment: 'Automatische Zahlung aktiviert', localReminders: 'Lokale Erinnerungen', localRemindersDetail: 'Fälligkeitserinnerungen auf diesem Gerät anzeigen.', remindMe: 'Erinnern', dueDay: 'Am Fälligkeitstag', dayBefore_one: '{{count}} Tag', dayBefore_other: '{{count}} Tage', notesOptional: 'Notizen (optional)',
      errors: { amountRequired: 'Geben Sie einen Betrag ein oder markieren Sie ihn als variabel.', invalidSchedule: 'Ungültiger Zeitplan', monthDates: 'Geben Sie einen oder mehrere Monatstage zwischen 1 und 31 ein.', weekday: 'Wählen Sie mindestens einen Wochentag.', saveTitle: 'Rechnung konnte nicht gespeichert werden', saveBody: 'Versuchen Sie es erneut.' },
    },
    bills: { archived: 'Archiviert', active: 'Aktiv', searchA11y: 'Rechnungen durchsuchen', noBills: 'Keine Rechnungen gefunden', syncPending: 'Änderungen warten auf die Synchronisierung.', variable: 'Variabel', shared: 'Geteilt', sharedBy: 'Geteilt von {{name}}', myPortion: 'Mein Anteil: {{amount}}', dueAgo_one: 'Vor {{count}} Tag fällig', dueAgo_other: 'Vor {{count}} Tagen fällig', dueToday: 'Heute fällig', dueIn_one: 'In {{count}} Tag fällig', dueIn_other: 'In {{count}} Tagen fällig', allCount: 'Alle ({{count}})', archivedCount: 'Archiviert ({{count}})', summary: '{{expenses}} Ausgaben · {{income}} Einnahmen', showing: '{{filter}}{{query}} · {{count}} Ergebnis', showing_other: '{{filter}}{{query}} · {{count}} Ergebnisse', matching: ' passend zu „{{query}}“', filterExpenses: 'Ausgaben', filterIncome: 'Einnahmen', filterArchived: 'archivierte Rechnungen', filterAll: 'Alle', noArchived: 'Keine archivierten Rechnungen', noMatches: 'Keine passenden Rechnungen', noBillsYet: 'Noch keine Rechnungen', adjustSearch: 'Passen Sie Suche oder Filter an.', addFirst: 'Fügen Sie Ihre erste Rechnung hinzu.', selectGroup: 'Rechnungsgruppe auswählen', filtersA11y: 'Rechnungsfilter{{active}}', activeFilters: ', {{count}} aktiv', filters: 'Filter', sortA11y: 'Rechnungen sortieren, {{sort}}', loadMoreA11y: 'Mehr Rechnungen laden, {{shown}} von {{total}} angezeigt', loadMore: 'Mehr laden · {{shown}} von {{total}}', reset: 'Zurücksetzen', filterTitle: 'Rechnungen filtern', dueDate: 'Fälligkeitsdatum', from: 'Von', to: 'Bis', dueFromA11y: 'Rechnungen fällig ab Datum', dueToA11y: 'Rechnungen fällig bis Datum', checkDue: 'Fälligkeitsdaten prüfen', invalidDue: 'Geben Sie Daten im Format JJJJ-MM-TT ein.', dueOrder: 'Das Startdatum muss vor oder am Enddatum liegen.', allAccounts: 'Alle Konten', allCategories: 'Alle Kategorien', sortTitle: 'Rechnungen sortieren', sortDueSoonest: 'Früheste Fälligkeit', sortDueLatest: 'Späteste Fälligkeit', sortNameAsc: 'Name A–Z', sortNameDesc: 'Name Z–A', sortHighest: 'Höchster Betrag', sortLowest: 'Niedrigster Betrag' },
    billDetail: { invalidAmount: 'Geben Sie einen gültigen Zahlungsbetrag ein.', recorded: 'Zahlung wurde erfasst.', recordFailed: 'Zahlung konnte nicht erfasst werden.', markedUnpaid: 'Anteil als unbezahlt markiert.', markedPaid: 'Anteil als bezahlt markiert.', updateFailed: 'Zahlungsstatus konnte nicht aktualisiert werden.', archiveFailed: 'Rechnung konnte nicht archiviert werden.', restoreFailed: 'Rechnung konnte nicht wiederhergestellt werden.', deleteOffline: 'Dauerhaftes Löschen erfordert eine aktive Verbindung. Sie können diese Rechnung offline archivieren.', deleteFailed: 'Rechnung konnte nicht gelöscht werden.', paymentNotesPlaceholder: 'Zahlungsnotizen hinzufügen…', notesPlaceholder: 'Notizen hinzufügen…', advanceDueA11y: 'Nächstes Fälligkeitsdatum verschieben', notFound: 'Rechnung nicht gefunden', goBack: 'Zurück', back: 'Zurück', nextDue: 'Nächste Fälligkeit', autoPay: 'Automatische Zahlung', yes: 'Ja', no: 'Nein', sharingDetails: 'Freigabedetails', myPortion: 'Mein Anteil', paymentStatus: 'Zahlungsstatus', paid: 'Bezahlt', notPaid: 'Nicht bezahlt', recordPayment: 'Zahlung erfassen', restore: 'Wiederherstellen', archive: 'Archivieren', shareBill: 'Rechnung teilen', deleteBill: 'Rechnung löschen', paymentHistory: 'Zahlungsverlauf', swipeHint: 'Zum Bearbeiten oder Löschen wischen', paymentDate: 'Zahlungsdatum', advanceDue: 'Nächstes Fälligkeitsdatum verschieben', advanceDueBody: 'Diese wiederkehrende Rechnung zum nächsten Termin verschieben.', record: 'Erfassen', editPayment: 'Zahlung bearbeiten', deletePayment: 'Zahlung löschen?', deletePaymentBody: 'Diese Zahlung wird dauerhaft entfernt.', updatePaymentFailed: 'Zahlung konnte nicht aktualisiert werden.', deletePaymentFailed: 'Zahlung konnte nicht gelöscht werden.' },
    payments: {
      title: 'Zahlungsverlauf', loadingTitle: 'Zahlungen werden geladen', loadingBody: 'Zahlungsverlauf und Summen werden abgerufen.', unavailableTitle: 'Zahlungen nicht verfügbar', unavailableBody: 'Der Zahlungsverlauf konnte nicht geladen werden.', restrictedTitle: 'Zahlungsverlauf eingeschränkt', restrictedBody: 'Ihre Rolle hat keinen Zugriff auf den Zahlungsverlauf.', count_one: '{{count}} Zahlung in {{bucket}}.', count_other: '{{count}} Zahlungen in {{bucket}}.', sortA11y: 'Zahlungen sortieren, {{sort}}', offlineSaved: 'Offline · gespeicherte Zahlungen werden angezeigt{{updated}}', netTotal: 'Nettosumme', totalsA11y: 'Zahlungssummen. Einnahmen {{income}}, Ausgaben {{expenses}}, Netto {{net}}', searchA11y: 'Zahlungsverlauf durchsuchen', searchPlaceholder: 'Rechnung, Konto, Kategorie oder Notiz durchsuchen', type: 'Zahlungstyp', filterA11y: 'Filter {{label}}', exportA11y: 'Zahlungsverlauf exportieren', exportFormatA11y: 'Zahlungsverlauf als {{format}}', payments: 'Zahlungen', emptyTitle: 'Keine passenden Zahlungen', emptyBody: 'Ändern Sie die Filter oder erfassen Sie eine Zahlung bei einer Rechnung.', pageA11y: 'Seite {{page}} von {{total}} laden', rowA11y: '{{name}}, {{direction}} {{amount}}, {{details}}{{pending}}', editA11y: 'Zahlung für {{name}} bearbeiten', deleteA11y: 'Zahlung für {{name}} löschen', deleteHint: 'Vor dem Löschen erscheint eine Bestätigung.', plus: 'plus', minus: 'minus', exportUnavailable: 'Export nicht verfügbar', exportFailed: 'Dieser Export konnte nicht erstellt werden.', checkDetails: 'Zahlungsdetails prüfen', invalidDetails: 'Geben Sie einen gültigen Betrag und ein Datum im Format JJJJ-MM-TT ein.', deleteTitle: 'Zahlung löschen?', deleteBody: 'Diese Zahlung und ihre Summen werden entfernt.', amountA11y: 'Zahlungsbetrag', dateA11y: 'Zahlungsdatum', notesA11y: 'Zahlungsnotizen', resetFilters: 'Filter auf „Alle“ zurücksetzen', any: 'Beliebig', anyAmount: 'Beliebiger Betrag', anyDate: 'Beliebiges Datum', allAccounts: 'Alle Konten', allCategories: 'Alle Kategorien', allBuckets: 'Alle Gruppen', print: 'Drucken', share: 'Teilen', filterDates: 'Zahlungsdaten', filterAmounts: 'Zahlungsbeträge', account: 'Konto', category: 'Kategorie', bucket: 'Gruppe', dateHelp: 'Wählen Sie einen Zeitraum oder geben Sie einen inklusiven benutzerdefinierten Bereich ein.', thisMonth: 'Dieser Monat', lastThreeMonths: 'Letzte 3 Monate', lastTwelveMonths: 'Letzte 12 Monate', customRange: 'Benutzerdefinierter Bereich', from: 'Von', through: 'Bis', fromDateA11y: 'Zahlungen ab Datum', throughDateA11y: 'Zahlungen bis Datum', applyDates: 'Benutzerdefinierte Daten anwenden', amountHelp: 'Nach absolutem Zahlungsbetrag filtern. Lassen Sie ein Feld leer, um den Bereich offen zu lassen.', minimumAmount: 'Mindestbetrag', maximumAmount: 'Höchstbetrag', minimumA11y: 'Mindestzahlungsbetrag', maximumA11y: 'Höchstzahlungsbetrag', noMinimum: 'Kein Mindestbetrag', noMaximum: 'Kein Höchstbetrag', applyAmount: 'Betragsbereich anwenden', checkDateRange: 'Datumsbereich prüfen', dateRequired: 'Geben Sie mindestens ein Datum im Format JJJJ-MM-TT ein.', dateOrder: 'Das Startdatum muss vor oder am Enddatum liegen.', checkAmountRange: 'Betragsbereich prüfen', amountRangeError: 'Geben Sie positive Beträge ein; der Mindestbetrag darf den Höchstbetrag nicht überschreiten.', fromDate: 'Ab {{date}}', throughDate: 'Bis {{date}}', sortTitle: 'Zahlungen sortieren', sortNewest: 'Neueste zuerst', sortOldest: 'Älteste zuerst', sortHighest: 'Höchster Betrag', sortLowest: 'Niedrigster Betrag', sortNameAsc: 'Rechnungsname A–Z', sortNameDesc: 'Rechnungsname Z–A', editPayment: 'Zahlung bearbeiten', saving: 'Speichern…', receivedShared: 'Erhaltene geteilte Zahlung · vom Zahler verwaltet', sharedManaged: 'Geteilte Zahlung · über die geteilte Rechnung verwaltet', billFallback: 'Rechnung {{id}}', currentBucket: 'Aktuelle Gruppe', exportTitle: 'BillManager-Zahlungsverlauf', csvDate: 'Datum', csvBill: 'Rechnung', csvBucket: 'Gruppe', csvAccount: 'Konto', csvCategory: 'Kategorie', csvDirection: 'Richtung', csvAmount: 'Betrag', csvNotes: 'Notizen',
    },
    analytics: {
      loadingTitle: 'Analysen werden geladen', loadingBody: 'Trends und Prognosen werden berechnet.', unavailableTitle: 'Analysen nicht verfügbar', unavailableBody: 'Analysen konnten nicht geladen werden.', restrictedTitle: 'Analysen eingeschränkt', restrictedBody: 'Ihre Rolle hat keinen Zugriff auf Analysen.', subtitle: 'Jahrestrends, Vergleiche und Prognosen für {{bucket}}.', yearA11y: 'Analysejahr {{year}}', chooseYear: 'Jahr auswählen', closeYearPicker: 'Jahresauswahl schließen', offlineSaved: 'Offline · letzter gespeicherter Analyse-Snapshot{{updated}}', annualSummary: 'Jahresübersicht', netCashFlow: 'Netto-Cashflow', yearComparison: '{{current}} im Vergleich zu {{previous}}', categories: 'Kategorien', accounts: 'Konten', noCategoryData: 'Keine Kategoriedaten für diesen Zeitraum.', noAccountData: 'Keine Kontodaten für diesen Zeitraum.', monthlyComparison: 'Monatsvergleich', yearlyView: 'Jahresansicht', cashFlowForecast: 'Cashflow-Prognose', forecast: 'Prognose', in: '{{amount}} Einnahmen', out: '{{amount}} Ausgaben', detailTitle: 'Analysedetail', detailBody: '{{section}} wird auf dieser Seite zusammengefasst und ist für Screenreader verfügbar.', notEnoughTitle: 'Noch nicht genug Aktivität', notEnoughBody: 'Erfassen Sie Zahlungen, um Monatstrends, Vergleiche und Cashflow-Prognosen zu erstellen.', range: 'Analysezeitraum', sixMonths: '6 Monate', twelveMonths: '12 Monate', year: 'Jahr', details: 'Details', openDetailsA11y: 'Details zu {{label}} öffnen', savingsRate: '{{value}} % Sparquote', yearOverYear: 'Jahresvergleich', netChange: 'Nettoveränderung', categoryTrends: 'Kategorietrends', byAccount: 'Nach Konto', noCategorized: 'Keine kategorisierten Ausgaben.', noAccounts: 'Keine Kontodaten.', yearlyHistory: 'Jahresverlauf', shareOfTotal: '{{value}} % der Gesamtsumme', priorPeriod: '{{value}} % zum vorherigen Zeitraum', up: 'gestiegen', down: 'gesunken', breakdownA11y: '{{label}}, {{amount}}, {{share}} Prozent{{change}}', changeA11y: ', {{direction}} um {{value}} Prozent', annualA11y: 'Jahresübersicht {{year}}. Einnahmen {{income}}, Ausgaben {{expenses}}, Netto {{net}}, Sparquote {{rate}} Prozent.', monthlyA11y: 'Monatsvergleich. {{summary}}', monthlyPointA11y: '{{label}}: Einnahmen {{income}}, Ausgaben {{expenses}}, Netto {{net}}', yearlyA11y: 'Jahresverlauf. {{summary}}', yearlyPointA11y: '{{year}} netto {{net}}', cashFlowA11y: 'Cashflow von {{first}} bis {{last}}. Der Endsaldo ändert sich von {{start}} auf {{end}}. {{count}} Prognosezeitraum.', cashFlowA11y_other: 'Cashflow von {{first}} bis {{last}}. Der Endsaldo ändert sich von {{start}} auf {{end}}. {{count}} Prognosezeiträume.', noCashFlowA11y: 'Keine Cashflow-Daten verfügbar.', currentBucket: 'Aktuelle Gruppe', yoyA11y: '{{current}} im Vergleich mit {{previous}}. Einnahmen {{incomeDirection}} um {{incomeValue}} Prozent. Ausgaben {{expenseDirection}} um {{expenseValue}} Prozent. Nettoveränderung {{net}}.',
    },
    collaboration: {
      loadingTitle: 'Geteilte Rechnungen werden geladen', loadingBody: 'Freigaben und Einladungen werden abgerufen.', unavailableTitle: 'Teilen nicht verfügbar', unavailableBody: 'Geteilte Rechnungen konnten nicht geladen werden.', restrictedTitle: 'Teilen eingeschränkt', restrictedBody: 'Ihre Rolle kann geteilte Rechnungen nicht anzeigen oder verwalten.', subtitle: 'Einladungen und Aufteilungen in {{bucket}}.', shareA11y: 'Rechnung teilen', shareBill: 'Rechnung teilen', offlineSaved: 'Offline · gespeicherte Freigabedaten{{updated}}. Stellen Sie zum Ändern von Zugriffen oder Einladungen eine Verbindung her.', emptyTitle: 'Keine geteilten Rechnungen', emptyBody: 'Teilen Sie eine Rechnung, um Ausgaben aufzuteilen und Zahlungen zu verfolgen.', pendingInvites: 'Ausstehende Einladungen ({{count}})', sharedBills: 'Geteilte Rechnungen ({{count}})', noActive: 'Keine aktiven geteilten Rechnungen.', invitationFrom: 'Einladung von {{name}}', invitationSent: 'Einladung an {{email}} gesendet', from: 'Von {{name}}', sentTo: 'Gesendet an {{email}}', acceptA11y: 'Einladung zu {{name}} annehmen', declineA11y: 'Einladung zu {{name}} ablehnen', revokeInviteA11y: 'Einladung an {{email}} widerrufen', ownedBy: 'Eigentümer: {{name}}', yourShare: 'Ihr Anteil', people_one: '{{count}} Person', people_other: '{{count}} Personen', openA11y: '{{name}}, {{owner}}, Ihr Anteil {{share}} von {{total}}, {{split}}, {{due}}{{pending}}. Geteilte Rechnung öffnen', editSplit: 'Aufteilung bearbeiten', editSplitA11y: 'Aufteilung für {{name}} bearbeiten', revoke: 'Widerrufen', stopSharingA11y: 'Freigabe von {{name}} beenden', revokeHint: 'Vor dem Widerrufen des Zugriffs erscheint eine Bestätigung.', revokeTitle: 'Rechnungsfreigabe widerrufen?', revokeBody: 'Der Empfänger verliert den Zugriff auf diese Rechnung.', equalSplit_one: 'Gleichmäßig mit {{count}} Person geteilt', equalSplit_other: 'Gleichmäßig mit {{count}} Personen geteilt', percentageSplit: '{{value}} Prozent Anteil', fixedSplit: 'Fester Anteil von {{amount}}', sent: 'Gesendet am {{date}}', you: 'Sie', supportRequired: 'Dieser BillManager-Server meldet keine Unterstützung für Freigaben.', noSavedData: 'Es sind noch keine gespeicherten Freigabedaten verfügbar. Stellen Sie eine Verbindung her und aktualisieren Sie einmal, um sie offline verfügbar zu machen.', sharesUnavailable: 'Freigaben für {{name}} sind nicht verfügbar.', acceptFailed: 'Geteilte Rechnung konnte nicht angenommen werden.', declineTitle: 'Einladung ablehnen?', declineBody: 'Diese Einladung zum Teilen einer Rechnung ablehnen?', declineFailed: 'Geteilte Rechnung konnte nicht abgelehnt werden.', leaveFailed: 'Geteilte Rechnung konnte nicht verlassen werden.', lastPaid: 'Zuletzt bezahlt: {{date}} ({{amount}})', lastPayment: 'Letzte Zahlung', counts: '{{active}} aktiv · {{pending}} ausstehend', emptyReceivedBody: 'Mit Ihnen geteilte Rechnungen erscheinen hier.', activeSharedBills: 'Aktive geteilte Rechnungen', leaveTitle: 'Geteilte Rechnung verlassen?', leaveBody: 'Diese geteilte Rechnung nicht mehr beobachten?', leave: 'Geteilte Rechnung verlassen',
    },
    settlements: { loadingTitle: 'Abrechnungen werden geladen', loadingBody: 'Geteilte Salden werden berechnet.', unavailableTitle: 'Abrechnungen nicht verfügbar', unavailableBody: 'Geteilte Salden konnten nicht geladen werden.', restrictedTitle: 'Abrechnungen eingeschränkt', restrictedBody: 'Ihre Rolle kann Abrechnungen nicht anzeigen.', offlineSaved: 'Offline · gespeicherte Abrechnungsdaten{{updated}}. Stellen Sie zum Ausgleichen eine Verbindung her.', connectionRequired: 'Für Abrechnungen ist eine Verbindung erforderlich.', noOpenBills: 'Keine offenen geteilten Rechnungen.', settleTitle: 'Diesen Saldo ausgleichen?', settleBody_one: '{{count}} geteilte Rechnung über {{amount}} wird als bezahlt markiert.', settleBody_other: '{{count}} geteilte Rechnungen über {{amount}} werden als bezahlt markiert.', historyTitle: 'Abrechnungsverlauf', historyBody_one: '{{count}} kürzlich abgerechnete Freigabe.', historyBody_other: '{{count}} kürzlich abgerechnete Freigaben.', subtitle: 'Salden aus geteilten Rechnungen in {{bucket}}.', supportRequired: 'Dieser BillManager-Server meldet keine Unterstützung für Abrechnungen.', noSavedData: 'Es sind noch keine gespeicherten Abrechnungsdaten verfügbar. Stellen Sie eine Verbindung her und aktualisieren Sie einmal, um sie offline verfügbar zu machen.', summaryA11y: 'Abrechnungsübersicht. Ihnen geschuldet {{owed}}, Sie schulden {{owe}}, Netto {{net}}', outstanding_one: '{{count}} offene Person', outstanding_other: '{{count}} offene Personen', people: 'Personen', settled: 'Ausgeglichen', owesYou: 'schuldet Ihnen', youOwe: 'Sie schulden', sharedBills_one: '{{count}} geteilte Rechnung', sharedBills_other: '{{count}} geteilte Rechnungen', personA11y: '{{name}}, {{direction}} {{amount}}, {{bills}}, {{activity}}{{pending}}. Abrechnungsdetails öffnen', markBalanceA11y: 'Saldo mit {{name}} als bezahlt markieren', connectHint: 'Stellen Sie zum Ausgleichen dieses Saldos eine Verbindung zum Server her.', markHint: 'Erfasst den vollständigen offenen Saldo als ausgeglichen.', everyoneSettled: 'Alle Salden sind ausgeglichen', everyoneSettledBody: 'Neue Salden erscheinen, nachdem geteilte Zahlungen erfasst wurden.', recent: 'Letzte Abrechnungen', viewAll: 'Alle anzeigen', noHistory: 'Noch kein Abrechnungsverlauf.', paid: '{{payer}} bezahlte {{payee}}', paidA11y: '{{payer}} bezahlte {{payee}} {{amount}}, {{date}}', openSharedBills: 'Offene geteilte Rechnungen' },
    administration: { loadingTitle: 'Verwaltung wird geladen', loadingBody: 'Nutzer, Einladungen und Rechnungsgruppen werden abgerufen.', unavailableTitle: 'Verwaltung nicht verfügbar', unavailableBody: 'Verwaltungsdaten konnten nicht geladen werden.', restrictedTitle: 'Administratorzugriff erforderlich', restrictedBody: 'Ihr Konto kann diesen Server nicht verwalten.', connectionTitle: 'Verbindung erforderlich', connectionBody: 'Die Verwaltung erfordert eine aktuelle Serververbindung.', subtitle: '{{users}} Nutzer · {{groups}} Rechnungsgruppen', users: 'Nutzer', invitations: 'Einladungen', groups: 'Rechnungsgruppen', role: 'Rolle: {{role}}', expires: 'Läuft am {{date}} ab', deleteUserTitle: 'Nutzer löschen?', deleteUserBody: 'Dieser Nutzer verliert den Zugriff auf alle zugewiesenen Rechnungsgruppen.', revokeInviteTitle: 'Einladung widerrufen?', revokeInviteBody: 'Der Einladungslink funktioniert anschließend nicht mehr.', permissionRequired: 'Nur Kontoinhaber und Administratoren können Nutzer, Einladungen und Rechnungsgruppen verwalten.', connectionFreshBody: 'Die Verwaltung lädt Berechtigungen und Verzeichnisdaten immer aktuell vom Server. Stellen Sie eine Verbindung her, um fortzufahren.', unavailableData: 'Verwaltungsdaten sind nicht verfügbar.', title: 'Verwaltung', manageAs: 'Personen und Datenzugriff als {{role}} verwalten.', section: 'Verwaltungsbereich', usersCount: 'Nutzer ({{count}})', invitesCount: 'Einladungen ({{count}})', groupsCount: 'Gruppen ({{count}})', pendingInvites: 'Ausstehende Einladungen', groupsAccess: 'Gruppen und Zugriff', addUser: 'Nutzer hinzufügen', inviteUser: 'Nutzer einladen', addGroup: 'Gruppe hinzufügen', noItems: 'Keine Einträge in {{section}}', startWith: 'Verwenden Sie „{{action}}“, um zu beginnen.', nothing: 'In diesem Bereich gibt es nichts zu verwalten.', audit: 'Administrative Änderungen werden vor weiteren Aktionen vom Server bestätigt und protokolliert.', noGroups: 'Keine Gruppen', lastLogin: 'letzte Anmeldung {{date}}', editA11y: '{{name}} bearbeiten', accessA11y: 'Zugriff für {{name}} ändern', deleteA11y: '{{name}} löschen', resendA11y: 'Einladung an {{email}} erneut senden', revokeA11y: 'Einladung an {{email}} widerrufen', manageAccessA11y: 'Zugriff für {{name}} verwalten', member_one: '{{count}} Mitglied', member_other: '{{count}} Mitglieder', owner_one: '{{count}} Eigentümer', owner_other: '{{count}} Eigentümer', invitedA11y: '{{email}}, als {{role}} von {{name}} eingeladen, {{groups}}, {{sent}}, {{expires}}', groupA11y: '{{name}}, {{members}}, {{owners}}{{database}}', databaseA11y: ', Datenbank {{name}}', userA11y: '{{name}}, {{email}}, {{role}}, {{status}}, {{groups}}{{lastLogin}}', noEmail: 'Keine E-Mail', groupFallback: 'Gruppe {{id}}', administrator: 'Administrator', statusActive: 'Aktiv', statusSuspended: 'Gesperrt', statusInvited: 'Eingeladen', statusPasswordChange: 'Passwortänderung erforderlich' },
    userManagement: {
      loadFailed: 'Nutzer konnten nicht geladen werden', cannotChangeOwnRole: 'Sie können Ihre eigene Rolle nicht ändern.', changeRoleTitle: 'Rolle ändern', changeRoleBody: '{{name}} von {{current}} zu {{next}} ändern?', updateRoleFailed: 'Rolle konnte nicht aktualisiert werden.', cannotDeleteOwn: 'Sie können Ihr eigenes Konto hier nicht löschen.', deleteTitle: 'Nutzer löschen?', deleteBody: '{{name}} löschen? Diese Aktion kann nicht rückgängig gemacht werden.', deleted: 'Nutzer wurde gelöscht.', deleteFailed: 'Nutzer konnte nicht gelöscht werden.', updated: 'Nutzer wurde aktualisiert.', updateFailed: 'Nutzer konnte nicht aktualisiert werden.', usernameRequired: 'Benutzername ist erforderlich.', passwordRequired: 'Passwort ist erforderlich.', passwordLength: 'Das Passwort muss mindestens 8 Zeichen lang sein.', chooseGroup: 'Wählen Sie mindestens eine Rechnungsgruppe aus.', created: 'Nutzer wurde erfolgreich erstellt.', createFailed: 'Nutzer konnte nicht erstellt werden.', you: 'Sie', joined: 'Beigetreten am {{date}}', demote: 'Herabstufen', promote: 'Hochstufen', title: 'Nutzerverwaltung', noUsers: 'Keine Nutzer gefunden', count_one: '{{count}} Nutzer', count_other: '{{count}} Nutzer', editUser: 'Nutzer bearbeiten', createUser: 'Nutzer erstellen', email: 'E-Mail', role: 'Rolle', usernameLabel: 'Benutzername *', usernamePlaceholder: 'Benutzernamen eingeben', emailOptional: 'E-Mail (optional)', passwordLabel: 'Passwort *', passwordPlaceholder: 'Mindestens 8 Zeichen', billGroupAccess: 'Zugriff auf Rechnungsgruppen *',
    },
    invitations: {
      loadFailed: 'Einladungen konnten nicht geladen werden', emailRequired: 'Geben Sie eine E-Mail-Adresse ein.', chooseGroup: 'Wählen Sie mindestens eine Rechnungsgruppe aus.', sent: 'Einladung wurde gesendet.', sendFailed: 'Einladung konnte nicht gesendet werden.', resendTitle: 'Einladung erneut senden?', resendBody: 'Einladung erneut an {{email}} senden?', resend: 'Erneut senden', resent: 'Einladung wurde erneut gesendet.', resendFailed: 'Einladung konnte nicht erneut gesendet werden.', cancelTitle: 'Einladung stornieren?', cancelBody: 'Einladung für {{email}} stornieren?', cancelAction: 'Ja, stornieren', cancelFailed: 'Einladung konnte nicht storniert werden.', expired: 'Abgelaufen', pending: 'Ausstehend', metadata: 'Rolle: {{role}} · Gesendet am {{date}}', expiredOn: 'Abgelaufen am {{date}}', expiresOn: 'Läuft am {{date}} ab', title: 'Einladungen', invite: 'Einladen', emailWarning: 'E-Mail ist nicht konfiguriert. Einladungs-E-Mails werden nicht automatisch gesendet. Teilen Sie den Einladungslink manuell.', noPending: 'Keine ausstehenden Einladungen', emptyBody: 'Tippen Sie auf „Einladen“, um einen neuen Nutzer einzuladen.', count_one: '{{count}} ausstehende Einladung', count_other: '{{count}} ausstehende Einladungen', inviteUser: 'Nutzer einladen', emailAddress: 'E-Mail-Adresse', billGroups: 'Rechnungsgruppen', sendInvite: 'Einladung senden',
    },
    groupManagement: {
      loadFailed: 'Rechnungsgruppen konnten nicht geladen werden', displayNameRequired: 'Geben Sie einen Anzeigenamen ein.', internalNameRequired: 'Geben Sie einen internen Namen ein.', updated: 'Rechnungsgruppe wurde aktualisiert.', created: 'Rechnungsgruppe wurde erstellt.', saveFailed: 'Rechnungsgruppe konnte nicht gespeichert werden.', deleteTitle: 'Rechnungsgruppe löschen?', deleteBody: '„{{name}}“ löschen? Dadurch werden alle Rechnungen und Zahlungen in dieser Gruppe dauerhaft gelöscht.', deleted: 'Rechnungsgruppe wurde gelöscht.', deleteFailed: 'Rechnungsgruppe konnte nicht gelöscht werden.', addAccessFailed: 'Nutzerzugriff konnte nicht hinzugefügt werden.', removeAccessTitle: 'Zugriff entfernen?', removeAccessBody: 'Zugriff von {{user}} auf „{{group}}“ entfernen?', removeAccessFailed: 'Nutzerzugriff konnte nicht entfernt werden.', accessCount_one: '{{count}} Nutzer mit Zugriff:', accessCount_other: '{{count}} Nutzer mit Zugriff:', manageUsers: 'Nutzer verwalten', deleteGroup: 'Gruppe löschen', title: 'Rechnungsgruppen', new: 'Neu', noGroups: 'Noch keine Rechnungsgruppen', emptyBody: 'Tippen Sie auf „Neu“, um Ihre erste Gruppe zu erstellen.', count_one: '{{count}} Rechnungsgruppe', count_other: '{{count}} Rechnungsgruppen', editTitle: 'Rechnungsgruppe bearbeiten', newTitle: 'Neue Rechnungsgruppe', internalName: 'Interner Name', internalPlaceholder: 'privat, geschäftlich usw.', immutable: 'Kann nach der Erstellung nicht geändert werden', displayName: 'Anzeigename', displayPlaceholder: 'Private Rechnungen, Geschäftsausgaben usw.', description: 'Beschreibung (optional)', descriptionPlaceholder: 'Wofür diese Rechnungsgruppe gedacht ist', manageAccess: 'Zugriff verwalten', usersWithAccess: 'Nutzer mit Zugriff', addUsers: 'Nutzer hinzufügen', noUsers: 'Keine Nutzer verfügbar',
    },
    billing: { loadingTitle: 'Abrechnung wird geladen', unavailableTitle: 'Abrechnung nicht verfügbar', unavailableBody: 'Abrechnungsinformationen konnten nicht geladen werden.', restrictedTitle: 'Abrechnungszugriff erforderlich', restrictedBody: 'Nur Kontoinhaber oder Administratoren können die Abrechnung verwalten.', connectionBody: 'Abrechnungsaktionen erfordern eine aktuelle Serververbindung.', openPortalA11y: 'Abrechnungsportal öffnen', checkoutFailed: 'Checkout konnte nicht gestartet werden.', portalFailed: 'Das Abrechnungsportal konnte nicht geöffnet werden.', selfHostedA11y: 'Unbegrenzter selbst gehosteter Tarif. Kein BillManager-Abonnement und keine Hosting-Nutzungslimits.', loadingPlan: 'Tarif und Nutzung werden geladen', loadingBody: 'Abonnementdetails werden abgerufen.', planUnavailable: 'Tarif- und Nutzungsdaten konnten nicht geladen werden.', ownerOnly: 'Nur Kontoinhaber können die Abrechnung anzeigen oder verwalten.', connectFresh: 'Stellen Sie eine Verbindung zu BillManager her, um aktuelle Abonnement-, Testzeitraum- und Nutzungsdaten zu laden.', titleSelfHosted: 'Selbst gehosteter Tarif', titleCloud: 'Tarif und Abrechnung', subtitleSelfHosted: 'Die Nutzung wird von Ihrem eigenen BillManager-Server verwaltet.', subtitleCloud: 'Abonnement, Testzeitraum und Bereitstellungsnutzung.', unlimitedSelfHosted: 'Unbegrenzt, selbst gehostet', selfHostedBody: 'Es ist kein BillManager-Abonnement erforderlich. Kapazität und Verfügbarkeit hängen von diesem Server ab.', trialA11y_one: 'Testzeitraum, {{count}} Tag verbleibend, endet am {{date}}', trialA11y_other: 'Testzeitraum, {{count}} Tage verbleibend, endet am {{date}}', trialRemaining_one: 'Noch {{count}} Tag im Testzeitraum', trialRemaining_other: 'Noch {{count}} Tage im Testzeitraum', ends: 'Endet am {{date}}', renews: 'Verlängert sich am {{date}}', accessEnds: 'Zugriff endet am {{date}}', noRenewal: 'Keine Verlängerung geplant', manage: 'Verwalten', usage: 'Nutzung', noUsage: 'Keine Nutzungsdaten', noUsageBody: 'Nutzungsdaten erscheinen, nachdem der Server den ersten Abrechnungszeitraum gemeldet hat.', availablePlans: 'Verfügbare Tarife', plansUnavailable: 'Tarife sind nicht verfügbar', plansUnavailableBody: 'Behalten Sie den aktuellen Tarif und versuchen Sie es nach der nächsten Katalogaktualisierung erneut.', current: 'Aktuell', recommended: 'Empfohlen', currentPlanA11y: ', aktueller Tarif', recommendedA11y: ', empfohlen', choose: '{{name}} auswählen', unlimitedUsage: '{{used}} {{unit}}, unbegrenzt', limitedUsage: '{{used}} von {{limit}} {{unit}}, {{percent}} Prozent verwendet', usageA11y: '{{label}}, {{usage}}', currentUsage: '{{used}} · Unbegrenzt', currentUsageLimited: '{{used}} / {{limit}} {{unit}}', perMonth: 'pro Monat', perYear: 'pro Jahr', basicDescription: 'Kernfunktionen für Planung, Analysen und Teilen', plusDescription: 'Mehr Familienmitglieder, Rechnungsgruppen und bevorzugter Zugriff', billsUnit: 'Rechnungen', groupsUnit: 'Gruppen', selfHostedUnlimited: 'Selbst gehostet, unbegrenzt', cancels: 'Endet am {{date}}' },
    deviceSecurity: { title: 'App-Sperre & Widget-Datenschutz', intro: 'Schützen Sie lokale Finanzdaten auf diesem Gerät.', biometricLock: 'Biometrische App-Sperre', biometricDetail: 'Beim Öffnen von BillManager Face ID, Touch ID oder Android-Biometrie anfordern.', unavailableTitle: 'Biometrie nicht verfügbar', unavailableBody: 'Richten Sie Face ID, Touch ID, Android-Biometrie oder einen Gerätecode in den Systemeinstellungen ein.', widgetAmounts: 'Beträge in Widgets anzeigen', widgetAmountsA11y: 'Beträge in Startbildschirm-Widgets anzeigen', widgetAmountsDetail: 'Beträge sind standardmäßig ausgeblendet. Das Aktivieren kann Finanzdaten auf Ihrem Startbildschirm sichtbar machen.', privacyDefault: 'Datenschutzfreundlicher Standard', privacyDefaultBody: 'Beträge in Benachrichtigungen und Widgets bleiben ausgeblendet, bis Sie sie ausdrücklich aktivieren.', screenTitle: 'Gerätesicherheit', screenIntro: 'Diese Einstellungen schützen lokale Daten und Erinnerungen auf diesem Gerät. Passkeys, 2FA und Wiederherstellungscodes werden vom Server verwaltet.', biometricBackground: 'BillManager sperren, nachdem die App im Hintergrund war.', reminderPermission: 'Berechtigung für lokale Erinnerungen', reminderAllowed: 'Auf diesem Gerät erlaubt', reminderDenied: 'Abgelehnt · Erinnerungen bleiben im Eingang', reminderReview: 'Systemberechtigung für Benachrichtigungen prüfen', widgetDetail: 'Beträge sind standardmäßig ausgeblendet und können bei gesperrtem Gerät sichtbar sein.', encryptedStorage: 'Rechnungen, Zahlungen, Konflikte und ausstehende Änderungen werden in einer SQLCipher-verschlüsselten SQLite-Datenbank gespeichert. Schlüsselmaterial und Anmeldedaten bleiben im sicheren Plattformspeicher.', passkeysSupported: 'Dieser Server unterstützt Passkeys. Öffnen Sie die Kontosicherheit, um Anmeldedaten und Wiederherstellungscodes zu verwalten.', passkeysUnsupported: 'Dieser Server meldet keine Passkey-Unterstützung.' },
    conflicts: { title: 'Synchronisierungskonflikte', subtitle: 'Wählen Sie die beizubehaltende Version. Destruktive Konflikte werden nie automatisch gelöst.', syncA11y: 'Jetzt synchronisieren', emptyTitle: 'Keine Synchronisierungskonflikte', emptyBody: 'Ihre Offline-Änderungen sind synchronisiert.', useServer: 'Serverversion verwenden', keepMine: 'Meine Änderungen behalten', useServerTitle: 'Serverversion verwenden?', useServerBody: 'Ihre ausstehenden Änderungen an diesem Element werden verworfen.', serverChanged: 'Serveränderung: {{date}}', reasonModified: 'Dieses Element wurde auf dem Server geändert.', reasonDeleted: 'Dieses Element wurde auf dem Server gelöscht.', reasonPermission: 'Ihre Berechtigung zum Ändern dieses Elements hat sich geändert.', screenTitle: 'Offline & Konflikte', synchronizing: 'Änderungen werden synchronisiert…', connected: 'Verbunden', offlineDetail: 'Offline · Änderungen bleiben auf diesem Gerät verschlüsselt', syncing: 'Synchronisierung…', syncNow: 'Jetzt synchronisieren', lastSync: 'Zuletzt synchronisiert: {{date}}', neverSynced: 'Dieser Arbeitsbereich wurde noch nicht vollständig synchronisiert.', noDecisions: 'Keine Entscheidung erforderlich', retryQueued: 'BillManager wiederholt ausstehende Änderungen in der richtigen Reihenfolge, sobald die Verbindung zurückkehrt.', changedAfterEdit: 'Der Server hat {{entity}} nach Ihrer Offline-Bearbeitung geändert.', serverUpdated: 'Serverversion aktualisiert: {{date}}', useServerA11y: 'Serverversion für {{name}} verwenden', keepMineA11y: 'Meine Änderungen für {{name}} behalten' },
    profiles: { title: 'Serverprofile', subtitle: 'Jeder Server verwaltet Anmeldedaten, Rechnungsgruppen, Cache und ausstehende Änderungen getrennt.', active: 'Aktiv', verified: 'Bestätigt: {{date}}', neverVerified: 'Noch nicht bestätigt', switchTitle: 'Server wechseln?', switchBody: 'BillManager beendet die aktuelle Sitzung und lädt den isolierten Arbeitsbereich dieses Servers.', switch: 'Wechseln', add: 'Selbst gehosteten Server hinzufügen', addTitle: 'Server hinzufügen', displayName: 'Anzeigename', displayNameA11y: 'Server-Anzeigename', displayNamePlaceholder: 'Heimserver', url: 'Server-URL', urlA11y: 'BillManager-Server-URL', verify: 'Prüfen & speichern', verifying: 'Wird geprüft…', httpsNotice: 'Produktionsprofile erfordern HTTPS mit einem systemweit vertrauenswürdigen Zertifikat.', serversTitle: 'Server', deploymentA11y: '{{name}}, {{mode}}', verifiedServer: 'Bestätigt · Server {{version}}', verificationRequired: 'Bestätigung erforderlich', verifyActive: 'Aktiven Server prüfen', checking: 'Wird geprüft…', addShort: 'Hinzufügen', verifyFailed: 'Dieser Server konnte nicht geprüft werden.', developmentNotice: 'Entwicklungs-Builds dürfen HTTP für lokale Tests verwenden.', validationNotice: 'BillManager prüft Zertifikatsvertrauen, Zustand, Funktionen und Mobile-Vertragskompatibilität, bevor das Profil gespeichert wird.', preparingA11y: 'BillManager wird vorbereitet', preparingWorkspace: 'Ihr sicherer Arbeitsbereich wird vorbereitet…' },
    upgrade: { title: 'Server-Upgrade erforderlich', body: 'Dieser BillManager-Server unterstützt den von dieser App benötigten Mobile-Vertrag nicht.', serverVersion: 'Serverversion', mobileContract: 'Mobile-Vertrag', requiredContract: 'Erforderlicher Vertrag', minimumAppVersion: 'Mobile-Mindestversion', verify: 'Erneut prüfen', verifyA11y: 'Serverkompatibilität erneut prüfen', anotherServer: 'Anderen Server verwenden', anotherServerA11y: 'Anderen BillManager-Server verwenden', help: 'Aktualisieren Sie den Server oder wählen Sie ein kompatibles Profil. Ihre lokalen Daten bleiben getrennt und verschlüsselt.', updateTitle: 'BillManager aktualisieren', versionBody: '{{profile}} erfordert Mobile-Version {{minimum}}. Auf diesem Gerät läuft {{current}}.', versionDetail: 'Ihre lokalen Daten wurden nicht geändert. Installieren Sie die neueste App-Version und prüfen Sie den Server erneut.', checking: 'Wird geprüft…', serverConnections: 'Serververbindungen', server: 'Server {{version}}' },
    widget: {
      nextUp: 'Als Nächstes',
      noUpcoming: 'Keine anstehenden Rechnungen',
      caughtUp: 'Alles ist erledigt',
      remainingThisMonth: '{{amount}} verbleiben diesen Monat',
    },
    share: { invalidPercentage: 'Geben Sie einen gültigen Prozentsatz zwischen 1 und 100 ein.', invalidFixed: 'Geben Sie einen gültigen festen Betrag ein.', success: 'Rechnung wurde geteilt.', revokeTitle: 'Freigabe widerrufen', revokeBody: 'Möchten Sie die Freigabe dieser Rechnung für diesen Nutzer wirklich beenden?', splitOptional: 'Aufteilung (optional)', none: 'Keine', percentagePlaceholder: 'Prozentsatz eingeben (zum Beispiel 50)', amountPlaceholder: 'Betrag eingeben', fullAmount: 'Voller Betrag', equal: '50/50', usernameOrEmail: 'Nutzername oder E-Mail', usernameOrEmailPlaceholder: 'Nutzername oder E-Mail eingeben', usernamePlaceholder: 'Nutzername eingeben' },
  },
} as const;
